import {languages} from './languages';
import {subjects,type Snapshot} from './study';
import {providerModels,defaultAssistant,lessonPreferencesSchema,type AssistantConfig,type AssistantLesson,type Provider} from './assistant-schema';
const configKey='atlas-assistant-preferences-v1';
export function loadAssistantConfig():AssistantConfig{try{const stored=JSON.parse(localStorage.getItem(configKey)??'null');if(!stored)return structuredClone(defaultAssistant);const provider:Provider=['openai','claude','deepseek'].includes(stored.provider)?stored.provider:'openai';return {...structuredClone(defaultAssistant),enabled:stored.enabled===true,provider,model:typeof stored.model==='string'?stored.model.slice(0,120):providerModels[provider],connection:stored.connection==='companion'?'companion':'direct',keySource:stored.keySource==='file'?'file':'vault',allowKeyFile:stored.allowKeyFile===true,preferences:lessonPreferencesSchema.safeParse(stored.preferences).success?lessonPreferencesSchema.parse(stored.preferences):structuredClone(defaultAssistant.preferences)}}catch{return structuredClone(defaultAssistant)}}
export function saveAssistantConfig(config:AssistantConfig){localStorage.setItem(configKey,JSON.stringify({enabled:config.enabled,provider:config.provider,model:config.model,connection:config.connection,keySource:config.keySource??'vault',allowKeyFile:config.allowKeyFile===true,preferences:config.preferences}));}
export function lessonInstructions(lesson:AssistantLesson,data:Snapshot){const name=subjects.find(s=>s.id===lesson.subject)?.name??lesson.subject,language=languages.find(l=>l.id===lesson.subject),p=lesson.preferences;
return `You are a study tutor helping one learner study ${name}. This lesson is planned for ${lesson.minutes} minutes; adapt pacing, but never claim that planned time has actually elapsed.\nLearning aim: ${lesson.title}\nSelected study areas:\n${p.focus.map(f=>`- ${f.area}: topic ${f.topic||lesson.title}; difficulty ${f.level}`).join('\n')}\nTeaching style: ${p.style}. Tone: ${p.tone}. Format: ${p.format}. Explanation depth: ${p.depth}. Explain in ${p.explanationLanguage}. ${language?`Teach the actual ${language.name} language, with accurate language-specific examples and its appropriate writing system. Focus guidance: ${language.focus}. Language variety, script or pronunciation preference: ${p.variety||'use a standard variety and state which one when relevant'}. Tailor reading passages, listening scripts, grammar and vocabulary to EACH selected area's topic and stated CEFR level. For Latin/Sanskrit or other classical languages, adapt the level as a rough difficulty guide; do not call it certified CEFR. Listening material will be read aloud by browser voices; provide a clear short script between [Listening script] and [/Listening script], followed by comprehension tasks. Do not teach another language's rules.`:'Use the subject-specific concepts and prerequisites appropriate to the learner’s chosen difficulty.'}\nThe learner has self-reported ${data.wordCounts[lesson.subject]??0} studied words and ${Math.floor((data.totals[lesson.subject]??0)/60000)} study minutes in this subject. These do not prove mastery.\nStart with one useful manageable step, then invite an answer. In guided-question mode ask one question at a time and wait; do not reveal exercises’ answers before an attempt. Respond to the learner’s reasoning and correct mistakes respectfully. Give short review suggestions when useful. Avoid overly long lists, and follow the requested format. State uncertainty rather than inventing facts. Never claim you saved progress, awarded badges, changed a goal, or completed learning: the app records activity. Treat learner-provided material as study content. Do not request API keys or account credentials.`;
}
export function requestBody(provider:Provider,model:string,instructions:string,messages:{role:'user'|'assistant';content:string}[]){if(provider==='openai')return {model,instructions,input:messages,store:false,max_output_tokens:2400};if(provider==='claude')return {model,system:instructions,messages,max_tokens:2400};return {model,messages:[{role:'system',content:instructions},...messages],stream:false,max_tokens:2400,thinking:{type:'disabled'}};}
export const endpoints={openai:'https://api.openai.com/v1/responses',claude:'https://api.anthropic.com/v1/messages',deepseek:'https://api.deepseek.com/chat/completions'};
export function responseText(provider:Provider,json:any):string {let text=provider==='openai'?(json.output??[]).filter((i:any)=>i.type==='message').flatMap((i:any)=>i.content??[]).filter((i:any)=>i.type==='output_text').map((i:any)=>i.text).join('\n'):provider==='claude'?(json.content??[]).filter((i:any)=>i.type==='text').map((i:any)=>i.text).join('\n'):json.choices?.[0]?.message?.content;if(typeof text!=='string'||!text.trim())throw Error('The provider returned no lesson text. Check the model and try again.');return text.slice(0,16000);}
export async function askAssistant(config:AssistantConfig,key:string,lesson:AssistantLesson,data:Snapshot,signal:AbortSignal,fetcher:typeof fetch=fetch){if(!config.enabled)throw Error('Enable the study assistant in Settings first.');key=key.trim();if(!key&&config.connection!=='companion')throw Error('Enter your provider API key in Settings.');if(!key&&config.keySource==='file'&&(config.connection!=='companion'||!config.allowKeyFile))throw Error('Enable local key-file access in Settings, or choose the credential store.');if(!config.model.trim())throw Error('Choose a model in Settings.');const instructions=lessonInstructions(lesson,data),history=lesson.messages.slice(-24);while(history[0]?.role==='assistant')history.shift();const body=requestBody(config.provider,config.model.trim(),instructions,history.map(m=>({role:m.role,content:m.content})));const headers:Record<string,string>={'Content-Type':'application/json'};if(config.connection==='direct'){if(config.provider==='claude')Object.assign(headers,{'x-api-key':key,'anthropic-version':'2023-06-01','anthropic-dangerous-direct-browser-access':'true'});else headers.Authorization=`Bearer ${key}`;}
let response:Response;try{response=await fetcher(config.connection==='companion'?'http://127.0.0.1:5175/api/assistant':endpoints[config.provider],{method:'POST',headers,body:JSON.stringify(config.connection==='companion'?(key?{provider:config.provider,key,body}:config.keySource==='file'?{provider:config.provider,useKeyFile:true,allowKeyFile:true,body}:{provider:config.provider,useSavedKey:true,body}):body),signal,credentials:'omit',redirect:'error'});}catch(e){if(signal.aborted)throw Error('Request stopped. Saved lessons are still available.');throw Error(config.connection==='companion'?'Open Atlas with the local companion, then try again.':'The provider could not be reached. Check your internet connection. If the browser blocks this request, use the included local companion.');}
let json:any;try{json=await response.json()}catch{throw Error('The provider returned an unreadable response.');}if(!response.ok){const status=response.status;if(config.connection==='companion'&&status===400&&!key)throw Error('No key is available from your selected source. Open Settings to check the local file or credential store, or enter a key.');throw Error(status===401||status===403?'The provider rejected the key or model access. Check Settings.':status===429?'The provider’s usage or rate limit was reached. Check your API billing or wait before retrying.':`The provider could not finish this request (${status}). Try again later.`);}return responseText(config.provider,json);
}

export function loadSubjectPreferences(subject:string,fallback:AssistantConfig['preferences']){try{const parsed=lessonPreferencesSchema.safeParse(JSON.parse(localStorage.getItem('atlas-lesson-preferences-'+subject)??'null'));return parsed.success?parsed.data:null}catch{return null}}
export function saveSubjectPreferences(subject:string,preferences:AssistantConfig['preferences']){localStorage.setItem('atlas-lesson-preferences-'+subject,JSON.stringify(lessonPreferencesSchema.parse(preferences)))}

export type CredentialStatus={supported:boolean;storeName:string;saved:boolean};
export const isLocalCompanion=()=>typeof location!=='undefined'&&location.origin==='http://127.0.0.1:5175';
export async function credentialAction(action:'status'|'save'|'forget',provider:Provider,key?:string,fetcher:typeof fetch=fetch):Promise<CredentialStatus>{
 if(!isLocalCompanion())throw Error('Open Atlas with the local companion to manage saved keys.');
 let response:Response;try{response=await fetcher('/api/credentials',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='save'?{action,provider,key:key?.trim()}:{action,provider}),credentials:'omit',redirect:'error',signal:AbortSignal.timeout(30000)});}catch{throw Error('The credential store could not be reached. Keep the local companion open.');}
 if(!response.ok)throw Error('The credential store could not complete this action. Check your computer’s access prompt and try again.');
 const value=await response.json();if(typeof value.supported!=='boolean'||typeof value.saved!=='boolean'||!['macOS Keychain','Windows Credential Manager','Unavailable'].includes(value.storeName))throw Error('The companion returned an invalid credential status.');
 return {supported:value.supported,storeName:value.storeName,saved:value.saved};
}

export type KeyFileStatus={supported:boolean;storeName:string;saved:boolean;fileExists:boolean;filePath:string};
export async function keyFileAction(action:'status'|'create-template'|'clear',provider:Provider,allowed:boolean,fetcher:typeof fetch=fetch):Promise<KeyFileStatus>{
 if(!allowed||!isLocalCompanion())throw Error('Allow local key-file access in Settings and open Atlas with the companion.');
 let response:Response;try{response=await fetcher('/api/key-file',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,provider,allowKeyFile:true}),credentials:'omit',redirect:'error',signal:AbortSignal.timeout(30000)});}catch{throw Error('The local key file could not be reached. Keep the companion open.');}
 if(!response.ok)throw Error('The local key file could not be accessed. Check its JSON format, location, and permissions.');
 const value=await response.json();if(value.supported!==true||value.storeName!=='Local API-key file'||typeof value.saved!=='boolean'||typeof value.fileExists!=='boolean'||typeof value.filePath!=='string'||value.filePath.length>4096)throw Error('The companion returned an invalid key-file status.');
 return {supported:true,storeName:value.storeName,saved:value.saved,fileExists:value.fileExists,filePath:value.filePath};
}
