import {defaults,subjectIds,subjects,registerCustomSubjects,type Snapshot,type SubjectId,type Session} from './study';
import {emptyWorkspace,type TopicDetail,type EvidenceFile} from './workspace';
import {allAwards,topicTracks} from './learning';
import {commandSchema} from './command-schema';
import {backupSchema} from './backup';
import {base64,fromBase64,fileType,MAX_FILE,MAX_STORAGE} from './files';
export type WordEntry={id:string;subject:SubjectId;count:number;created_at:number};
export type State={version:1;data:Snapshot;wordEntries:WordEntry[];fileData:Record<string,Blob>;configured:boolean;savedAt:number;lastBackupAt:number};
export function blankState():State{return {version:1,data:{customSubjects:[],workspace:structuredClone(emptyWorkspace),goalEffort:{},sessionCount:0,completedCount:0,topics:[],badges:[],wordCounts:{},sessions:[],active:null,goals:[],settings:structuredClone(defaults),totals:Object.fromEntries(subjectIds.map(id=>[id,0])) as Snapshot['totals'],serverNow:0},wordEntries:[],fileData:{},configured:false,savedAt:0,lastBackupAt:0}}
let connection:Promise<IDBDatabase>|undefined;
export function openDatabase(){return connection??=new Promise<IDBDatabase>((resolve,reject)=>{try{const r=indexedDB.open('atlas-study-world-offline',1);r.onupgradeneeded=()=>r.result.createObjectStore('workspace');r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();connection=undefined};resolve(r.result)};r.onerror=()=>{connection=undefined;reject(Error('Local storage could not open. Use a normal Chrome or Edge window and allow browser storage.'))};r.onblocked=()=>{connection=undefined;reject(Error('Close other Atlas tabs and retry.'))}}catch{connection=undefined;reject(Error('This browser blocks local-file storage. Open this HTML in Chrome or Edge, or use the included local launcher.'))}})}
// Each mutation reads the latest committed state inside one exclusive IDB transaction.
// Acknowledgement happens only at transaction completion, including attached Blobs.
export async function transact<T>(change:(state:State)=>T,write=true):Promise<T>{const db=await openDatabase();return new Promise<T>((resolve,reject)=>{let result:T;let failure:unknown;let originalCustom:Snapshot['customSubjects']=[];const tx=db.transaction('workspace',write?'readwrite':'readonly',write?{durability:'strict'}:undefined),store=tx.objectStore('workspace'),read=store.get('main');read.onsuccess=()=>{try{const state:State=read.result??blankState();originalCustom=structuredClone(state.data.customSubjects??[]);result=change(state);if(write){checkLimits(state);state.savedAt=Date.now();store.put(state,'main')}}catch(e){failure=e;registerCustomSubjects(originalCustom);tx.abort()}};tx.oncomplete=()=>resolve(result!);tx.onabort=()=>{registerCustomSubjects(originalCustom);reject(failure??tx.error??Error('Progress could not save. Download a backup and check available disk space.'))};tx.onerror=()=>{failure??=tx.error}})}
function used(s:Session,now:number){return Math.min(s.planned_seconds*1000,s.accumulated_ms+(s.status==='running'&&s.running_since!==null?Math.max(0,now-s.running_since):0))}
export function settle(state:State,now=Date.now()){const d=state.data;d.customSubjects??=[];d.workspace.horizonGoals??=[];d.workspace.journal??=[];d.wordEntries=state.wordEntries;registerCustomSubjects(d.customSubjects);for(const s of d.sessions)if(s.status==='running'&&s.running_since!==null&&used(s,now)>=s.planned_seconds*1000){s.ended_at=s.running_since+Math.max(0,s.planned_seconds*1000-s.accumulated_ms);s.accumulated_ms=s.credited_ms=s.planned_seconds*1000;s.running_since=null;s.status='completed'}d.totals=Object.fromEntries([...subjectIds,...d.customSubjects.map(s=>s.id)].map(id=>[id,0])) as Snapshot['totals'];d.goalEffort={};d.sessionCount=0;d.completedCount=0;for(const s of d.sessions){d.totals[s.subject]+=s.credited_ms;if(s.goal_id)d.goalEffort[s.goal_id]=(d.goalEffort[s.goal_id]??0)+s.credited_ms;if(s.status==='completed'||s.status==='stopped')d.sessionCount++;if(s.status==='completed')d.completedCount++}d.active=d.sessions.find(s=>s.status==='running'||s.status==='paused')??null;d.workspace.wordReviewTotals={};for(const r of d.workspace.wordReviews)d.workspace.wordReviewTotals[r.subject]=(d.workspace.wordReviewTotals[r.subject]??0)+r.count;d.serverNow=now;const existing=new Set(d.badges.map(b=>b.badge_id));for(const a of allAwards(d))if(a.eligible&&!existing.has(a.id))d.badges.push({badge_id:a.id,subject:a.subject,earned_at:now});return d}
function builtin(id:string){for(const [subject,items]of Object.entries(topicTracks)){const t=items.find(t=>t.id===id);if(t)return {...t,subject:subject as SubjectId}}}
function ensureTopic(d:Snapshot,id:string,now:number):TopicDetail{const existing=d.workspace.topics.find(t=>t.topic_id===id);if(existing)return existing;const t=builtin(id);if(!t)throw Error('Choose a topic in your learning path.');const learned=d.topics.some(p=>p.topic_id===id&&p.learned);const next:TopicDetail={topic_id:id,subject:t.subject,title:t.title,custom:0,note:'',blocker:'',next_step:'',level:learned?2:0,review_at:learned?now:null,review_interval:1,review_count:0,last_reviewed:null,updated_at:now};d.workspace.topics.push(next);return next}
function mark(d:Snapshot,t:TopicDetail,now:number){let p=d.topics.find(p=>p.topic_id===t.topic_id);if(!p){p={topic_id:t.topic_id,subject:t.subject,learned:0,learned_at:null};d.topics.push(p)}p.learned=t.level>=2?1:0;p.learned_at=p.learned?p.learned_at??now:null}
export function mutate(state:State,input:unknown,now=Date.now()):Snapshot{const parsed=commandSchema.safeParse(input);if(!parsed.success)throw Error('Check the details and try again.');const c=parsed.data,d=settle(state,now),w=d.workspace;
 const session=(id:string)=>{const s=d.sessions.find(s=>s.id===id);if(!s)throw Error('Study session not found.');return s};
 const topicMatches=(id:string,subject:SubjectId)=>{const t=builtin(id)??w.topics.find(t=>t.topic_id===id);if(!t||t.subject!==subject)throw Error('Choose a topic in this subject.')};
 if('subject' in c&&!subjects.some(s=>s.id===c.subject))throw Error('Choose an offered subject or add your own first.');
 switch(c.action){
 case 'journal-save':{const existing=w.journal.find(e=>e.id===c.id),{action,...entry}=c;if(existing)Object.assign(existing,entry,{updated_at:now});else w.journal.unshift({...entry,created_at:now,updated_at:now});break}
 case 'subject-create':{const id=`custom-${c.id}` as const;if(d.customSubjects.some(s=>s.id===id))break;if(d.customSubjects.some(s=>s.name.toLowerCase()===c.name.toLowerCase())||subjects.some(s=>s.name.toLowerCase()===c.name.toLowerCase()))throw Error('This subject is already in your list.');d.customSubjects.push({id,name:c.name,color:'#b4f2cf',glyph:'✦'});break}
 case 'horizon-goal-add':if(!w.horizonGoals.some(g=>g.id===c.id))w.horizonGoals.unshift({id:c.id,horizon:c.horizon,title:c.title,done:false,created_at:now,completed_at:null});break;
 case 'horizon-goal-update':{const g=w.horizonGoals.find(g=>g.id===c.id);if(!g)throw Error('Goal not found.');g.done=c.done;g.completed_at=c.done?g.completed_at??now:null;break}

 case 'start':{if(d.sessions.some(s=>s.id===c.id))break;if(d.active)throw Error('A focus session is already active. Finish it first.');if(c.goalId&&!d.goals.some(g=>g.id===c.goalId&&g.subject===c.subject&&!g.completed_at&&!g.paused))throw Error('Choose an active quest in this subject.');if(c.topicId)topicMatches(c.topicId,c.subject);d.sessions.unshift({id:c.id,subject:c.subject,goal_id:c.goalId??null,topic_id:c.topicId??null,planned_seconds:c.seconds,accumulated_ms:0,running_since:now,status:'running',credited_ms:0,started_at:now,ended_at:null,note:''});break}
 case 'pause':{const s=session(c.id);if(s.status==='running'){s.accumulated_ms=used(s,now);s.running_since=null;s.status='paused'}break}
 case 'resume':{const s=session(c.id);if(s.goal_id&&d.goals.some(g=>g.id===s.goal_id&&g.paused))throw Error('Resume this quest before resuming focus.');if(s.status==='paused'){s.status='running';s.running_since=now}break}
 case 'finish':{const s=session(c.id);if(s.status==='running'||s.status==='paused'){s.accumulated_ms=s.credited_ms=used(s,now);s.ended_at=now;s.running_since=null;s.status='stopped'}break}
 case 'words-add':if(!state.wordEntries.some(e=>e.id===c.id)){if((d.wordCounts[c.subject]??0)+c.count>1000000)throw Error('This language can track up to 1,000,000 words.');d.wordCounts[c.subject]=(d.wordCounts[c.subject]??0)+c.count;state.wordEntries.push({id:c.id,subject:c.subject,count:c.count,created_at:now})}break;
 case 'words-set':d.wordCounts[c.subject]=c.count;break;
 case 'words-review':if(!w.wordReviews.some(r=>r.id===c.id))w.wordReviews.unshift({id:c.id,subject:c.subject,count:c.count,created_at:now});break;
 case 'goal-create':if(!d.goals.some(g=>g.id===c.id))d.goals.unshift({id:c.id,subject:c.subject,title:c.title,reason:c.reason,target_date:c.targetDate,steps:c.steps,started_at:now,completed_at:null,note:'',paused:0,next_step:'',estimated_minutes:null});break;
 case 'goal-update':{const g=d.goals.find(g=>g.id===c.id);if(!g)throw Error('Quest not found.');g.steps=c.steps;g.completed_at=c.completed?g.completed_at??now:null;if(c.note!==undefined)g.note=c.note;break}
 case 'goal-plan':{const g=d.goals.find(g=>g.id===c.id);if(!g)throw Error('Quest not found.');g.paused=c.paused?1:0;g.next_step=c.nextStep;g.estimated_minutes=c.estimatedMinutes;if(c.paused)for(const s of d.sessions)if(s.goal_id===c.id&&s.status==='running'){s.accumulated_ms=used(s,now);s.running_since=null;s.status='paused'}break}
 case 'session-note':session(c.id).note=c.note;break;
 case 'settings':for(const [id,badge]of Object.entries(c.settings.equipped))if(!d.badges.some(b=>b.subject===id&&b.badge_id===badge))throw Error('Earn this reward before displaying it.');d.settings=c.settings;state.configured=true;break;
 case 'topic-create':if(builtin(c.id))throw Error('Choose a unique personal topic.');if(!w.topics.some(t=>t.topic_id===c.id))w.topics.push({topic_id:c.id,subject:c.subject,title:c.title,custom:1,note:c.note,blocker:'',next_step:'',level:0,review_at:null,review_interval:1,review_count:0,last_reviewed:null,updated_at:now});break;
 case 'topic-note':{const t=ensureTopic(d,c.topicId,now);t.note=c.note;t.blocker=c.blocker;t.next_step=c.nextStep;t.updated_at=now;break}
 case 'topic-update':{const t=ensureTopic(d,c.topicId,now);t.level=c.learned?Math.max(t.level,2):0;t.review_at=c.learned?t.review_at??now+86400000:null;t.updated_at=now;mark(d,t,now);break}
 case 'topic-level':{const t=ensureTopic(d,c.topicId,now);t.level=c.level;t.review_at=c.level?t.review_at??now+86400000:null;t.updated_at=now;mark(d,t,now);break}
 case 'topic-review':{const t=ensureTopic(d,c.topicId,now);if(!t.level)throw Error('Study this topic before logging a review.');const interval=c.confidence==='easy'?Math.min(60,Math.max(2,t.review_interval*2)):c.confidence==='uncertain'?Math.max(1,Math.round(t.review_interval/2)):1;t.review_interval=interval;t.review_at=now+(c.confidence==='practice'?4*3600000:interval*86400000);t.review_count++;t.last_reviewed=t.updated_at=now;break}
 case 'review-later':{const t=ensureTopic(d,c.topicId,now);t.review_at=now+c.days*86400000;t.updated_at=now;break}
 case 'practice-add':if(c.topicId)topicMatches(c.topicId,c.subject);if(!w.practice.some(p=>p.id===c.id))w.practice.unshift({id:c.id,subject:c.subject,topic_id:c.topicId,title:c.title,reflection:c.reflection,link:c.link,completed_at:now});break;
 case 'planner-settings':w.preferences={...c.preferences,days:[...new Set(c.preferences.days)],priorities:[...new Set(c.preferences.priorities)]};state.configured=true;break;
 case 'day-mode':{const m=w.dayModes.find(m=>m.day===c.day);if(m)m.mode=c.mode;else w.dayModes.unshift({day:c.day,mode:c.mode});break}
 case 'weekly-reflection':{const r=w.reflections.find(r=>r.week===c.week),next={week:c.week,helped:c.helped,difficult:c.difficult,next:c.next,updated_at:now};if(r)Object.assign(r,next);else w.reflections.unshift(next);break}
 }
 return settle(state,now);
}
export function addFile(state:State,file:EvidenceFile,bytes:Uint8Array){if(bytes.length!==file.size||fileType(bytes,file.filename)!==file.content_type)throw Error('This attachment is invalid.');if(file.size>MAX_FILE||!file.size)throw Error('Files can be up to 5 MB.');if(!subjects.some(s=>s.id===file.subject))throw Error('Choose a valid subject.');if(file.topic_id){const t=builtin(file.topic_id)??state.data.workspace.topics.find(t=>t.topic_id===file.topic_id);if(!t||t.subject!==file.subject)throw Error('Choose a topic in this subject.')}if(state.data.workspace.files.some(f=>f.id===file.id))return;if(state.data.workspace.files.reduce((sum,f)=>sum+f.size,0)+bytes.length>MAX_STORAGE)throw Error('The file gallery can hold up to 20 MB.');state.data.workspace.files.unshift(file);state.fileData[file.id]=new Blob([new Uint8Array(bytes)],{type:file.content_type});}
export function mergeBackup(state:State,input:unknown,now=Date.now()){const parsed=backupSchema.safeParse(input);if(!parsed.success)throw Error('This is not a valid Atlas backup. Your progress has not changed.');const b=parsed.data,d=state.data,w=d.workspace;
 uniqueCustom(b.customSubjects);const customIds=new Set([...d.customSubjects,...b.customSubjects].map(s=>s.id));for(const s of b.customSubjects){const own=d.customSubjects.find(o=>o.id===s.id);if(own&&own.name!==s.name)throw Error('A custom subject has a conflicting name.');}const validSubjects=new Set<string>([...subjectIds,...customIds]);for(const row of [...b.sessions,...b.goals,...b.topics,...b.badges,...b.wordEntries??[],...b.workspace?.topics??[],...b.workspace?.practice??[],...b.workspace?.wordReviews??[],...b.fileData??[]])if(!validSubjects.has(row.subject))throw Error('The backup references a missing custom subject.');for(const id of [...Object.keys(b.wordCounts),...Object.keys(b.settings.equipped),...b.workspace?.preferences.priorities??[]])if(!validSubjects.has(id))throw Error('The backup references a missing custom subject.');
 const allCustom=[...d.customSubjects,...b.customSubjects.filter(s=>!d.customSubjects.some(o=>o.id===s.id))];registerCustomSubjects(allCustom);
 const unique=(rows:string[])=>{if(new Set(rows).size!==rows.length)throw Error('The backup contains duplicate identifiers.')};for(const rows of [b.sessions,b.goals,b.wordEntries??[],b.workspace?.practice??[],b.workspace?.wordReviews??[],b.fileData??[]])unique(rows.map(r=>r.id));for(const rows of [b.topics,b.workspace?.topics??[]])unique(rows.map(r=>r.topic_id));unique(b.badges.map(b=>b.badge_id));unique((b.workspace?.files??[]).map(f=>f.id));unique((b.workspace?.reflections??[]).map(r=>r.week));unique((b.workspace?.dayModes??[]).map(r=>r.day));
 const goals=new Map([...b.goals,...d.goals].map(g=>[g.id,g.subject])),practice=new Map([...(b.workspace?.practice??[]),...w.practice].map(p=>[p.id,p.subject]));
 const known=new Map(Object.entries(topicTracks).flatMap(([subject,items])=>items.map(t=>[t.id,subject] as const)));for(const t of b.workspace?.topics??[])if(t.custom){if(known.has(t.topic_id)||!/^[a-f0-9-]{36}$/i.test(t.topic_id))throw Error('A personal topic conflicts with a built-in topic.');known.set(t.topic_id,t.subject)}for(const t of w.topics){if(known.has(t.topic_id)&&known.get(t.topic_id)!==t.subject)throw Error('A topic has a conflicting subject.');known.set(t.topic_id,t.subject)}
 const ref=(id:string|null|undefined,subject:SubjectId)=>{if(id&&known.get(id)!==subject)throw Error('A topic reference is invalid.')};
 for(const t of [...b.topics,...b.workspace?.topics??[]]){if(known.get(t.topic_id)!==t.subject)throw Error('The backup contains an invalid topic.')}for(const g of b.goals){if(d.goals.some(o=>o.id===g.id&&o.subject!==g.subject))throw Error('A quest has a conflicting subject.');unique(g.steps.map(s=>s.id))}for(const s of b.sessions){if(s.goal_id&&goals.get(s.goal_id)!==s.subject)throw Error('A session has an invalid quest.');ref(s.topic_id,s.subject)}for(const p of b.workspace?.practice??[])ref(p.topic_id,p.subject);
 const knownAwards=new Map(allAwards({...blankState().data,workspace:{...structuredClone(emptyWorkspace),topics:[...w.topics,...b.workspace?.topics??[]]}}).map(a=>[a.id,a.subject]));for(const badge of b.badges)if(knownAwards.get(badge.badge_id)!==badge.subject)throw Error('The backup contains an unknown achievement.');for(const [subject,id]of Object.entries(b.settings.equipped))if(!b.badges.some(badge=>badge.subject===subject&&badge.badge_id===id))throw Error('The backup displays an unearned achievement.');
 const files=b.fileData??[],fileIds=(b.workspace?.files??[]).map(f=>f.id);if(files.length!==fileIds.length||files.some(f=>!fileIds.includes(f.id)))throw Error('The backup file list and attachment contents do not match.');const decoded=files.map(f=>{ref(f.topic_id,f.subject);if(f.practice_id&&practice.get(f.practice_id)!==f.subject)throw Error('A file has an invalid practice reference.');const bytes=fromBase64(f.data);if(bytes.length!==f.size||fileType(bytes,f.filename)!==f.content_type)throw Error('A backup attachment is invalid.');return {file:f,bytes}});if(w.files.reduce((n,f)=>n+f.size,0)+decoded.filter(f=>!w.files.some(old=>old.id===f.file.id)).reduce((n,f)=>n+f.bytes.length,0)>MAX_STORAGE)throw Error('The merged gallery would exceed 20 MB.');
 const merge=<T>(current:T[],incoming:T[],key:(r:T)=>string)=>{const ids=new Set(current.map(key));for(const row of incoming)if(!ids.has(key(row))){current.push(row);ids.add(key(row))}};
 merge(d.customSubjects,b.customSubjects as typeof d.customSubjects,s=>s.id);merge(d.goals,b.goals,g=>g.id);merge(d.sessions,b.sessions.filter(s=>['completed','stopped'].includes(s.status)&&s.ended_at!==null).map(s=>({...s,running_since:null,topic_id:s.topic_id??null})),s=>s.id);merge(d.topics,b.topics,t=>t.topic_id);merge(d.badges,b.badges,b=>b.badge_id);merge(state.wordEntries,b.wordEntries??[],e=>e.id);for(const [subject,count]of Object.entries(b.wordCounts))d.wordCounts[subject as SubjectId]=Math.max(d.wordCounts[subject as SubjectId]??0,count??0);if(!state.configured){d.settings=b.settings;if(b.workspace)w.preferences=b.workspace.preferences;state.configured=true}
 if(b.workspace){unique(b.workspace.horizonGoals.map(g=>g.id));unique(b.workspace.journal.map(j=>j.id));merge(w.journal,b.workspace.journal,e=>e.id);merge(w.horizonGoals,b.workspace.horizonGoals,g=>g.id);merge(w.topics,b.workspace.topics,t=>t.topic_id);merge(w.practice,b.workspace.practice,p=>p.id);merge(w.wordReviews,b.workspace.wordReviews,r=>r.id);merge(w.reflections,b.workspace.reflections,r=>r.week);merge(w.dayModes,b.workspace.dayModes,r=>r.day)}
 for(const {file,bytes}of decoded){const {data,...metadata}=file;addFile(state,metadata,bytes)}for(const t of w.topics)mark(d,t,now);return settle(state,now);
}
export async function exportBackup(){const state=await transact(s=>{settle(s);s.lastBackupAt=Date.now();return s});const fileData=[];for(const f of state.data.workspace.files){const blob=state.fileData[f.id];if(!blob)throw Error('An attachment is unavailable. Retry before making a backup.');fileData.push({...f,data:base64(new Uint8Array(await blob.arrayBuffer()))})}return {format:'atlas-study-backup',version:2,exportedAt:new Date().toISOString(),...state.data,wordEntries:state.wordEntries,fileData}}

function uniqueCustom(items:{id:string}[]){if(new Set(items.map(s=>s.id)).size!==items.length)throw Error('The backup has duplicate custom subjects.');}
function checkLimits(s:State){const d=s.data,w=d.workspace;if(new TextEncoder().encode(JSON.stringify({...d,wordEntries:s.wordEntries})).length+w.files.reduce((n,f)=>n+Math.ceil(f.size/3)*4+1000,0)>35*1024*1024)throw Error('This workspace is reaching its backup size limit. Export a backup before adding more.');for(const [count,limit,label]of [[d.sessions.length,10000,'sessions'],[d.goals.length,2000,'quests'],[d.customSubjects.length,100,'custom subjects'],[d.topics.length,2000,'topic records'],[d.badges.length,50000,'badges'],[s.wordEntries.length,20000,'word entries'],[w.topics.length,2000,'personal topics'],[w.practice.length,2000,'practice entries'],[w.files.length,200,'attachments'],[w.wordReviews.length,10000,'word reviews'],[w.reflections.length,1000,'weekly reflections'],[w.dayModes.length,4000,'daily records'],[w.horizonGoals.length,2000,'planning goals'],[w.journal.length,2000,'journal entries']] as const)if(count>limit)throw Error(`The local workspace limit of ${limit} ${label} has been reached. Export a backup before starting a new workspace.`);}
