import {Document,Packer,Paragraph,TextRun,HeadingLevel} from 'docx';
export type Report={title:string;subtitle:string;sections:{heading:string;lines:string[]}[]};
const escape=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function markdown(r:Report){return `# ${r.title}\n\n${r.subtitle}\n\n`+r.sections.map(s=>`## ${s.heading}\n\n${s.lines.join('\n\n')}`).join('\n\n')+'\n'}
export function plainText(r:Report){return `${r.title}\n${r.subtitle}\n\n`+r.sections.map(s=>`${s.heading}\n${s.lines.join('\n\n')}`).join('\n\n')+'\n'}
export function reportHtml(r:Report){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(r.title)}</title><style>${printStyle}</style></head><body><div class="report-tools"><button onclick="window.print()">Print / Save PDF</button></div><article class="atlas-report"><p class="report-brand">ATLAS · STUDY WORLD</p><h1>${escape(r.title)}</h1><p class="report-subtitle">${escape(r.subtitle)}</p>${r.sections.map(s=>`<section><h2>${escape(s.heading)}</h2>${s.lines.map(l=>`<p>${escape(l)}</p>`).join('')}</section>`).join('')}<footer>Small steps. A growing world.</footer></article></body></html>`}
const printStyle=`@page{size:auto;margin:18mm}*{box-sizing:border-box}body{margin:0;background:#eaf1ea;color:#152b2a;font:16px/1.6 system-ui,sans-serif}.atlas-report{max-width:900px;margin:30px auto;padding:50px;background:white}.report-brand{font-size:12px;letter-spacing:3px;color:#537267}h1{font-size:38px;line-height:1.2}h2{font-size:21px;color:#295844;margin:32px 0 12px;border-bottom:1px solid #c4d3c7;padding-bottom:10px}.atlas-report p{white-space:pre-wrap;overflow-wrap:anywhere}.report-subtitle{color:#64776b}section{break-inside:auto}h2{break-after:avoid}footer{margin-top:42px;color:#738276;font-size:12px}.report-tools{max-width:900px;margin:20px auto}.report-tools button{padding:12px 22px;border:0;border-radius:10px;background:#295844;color:white}@media print{body{background:white}.report-tools{display:none}.atlas-report{padding:0;margin:0;max-width:none}h1{font-size:30px}p{orphans:3;widows:3}}`;
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.style.display="none";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
export async function wordBlob(r:Report){const paragraphs=[new Paragraph({text:r.title,heading:HeadingLevel.TITLE}),new Paragraph({text:r.subtitle}),...r.sections.flatMap(s=>[new Paragraph({text:s.heading,heading:HeadingLevel.HEADING_1}),...s.lines.flatMap(l=>l.split("\n").map(text=>new Paragraph({children:[new TextRun(text)],spacing:{after:160}})))])];return Packer.toBlob(new Document({sections:[{children:paragraphs}]}))}
export async function downloadReport(r:Report,format:'html'|'md'|'txt'|'docx',name:string){if(format==='docx'){downloadBlob(await wordBlob(r),name+'.docx');return}const text=format==='html'?reportHtml(r):format==='md'?markdown(r):plainText(r);downloadBlob(new Blob([text],{type:format==='html'?'text/html;charset=utf-8':format==='md'?'text/markdown;charset=utf-8':'text/plain;charset=utf-8'}),name+'.'+format)}
export function printReport(r:Report){const old=document.title,node=document.createElement('div');node.id='atlas-print';const style=document.createElement('style');style.textContent=printStyle+'#atlas-print{display:none}@media print{body>*:not(#atlas-print){display:none!important}#atlas-print{display:block!important}}';const article=document.createElement('article');article.className='atlas-report';const add=(tag:string,text:string,parent:HTMLElement=article)=>{const e=document.createElement(tag);e.textContent=text;parent.appendChild(e);return e};add('p','ATLAS · STUDY WORLD').className='report-brand';add('h1',r.title);add('p',r.subtitle).className='report-subtitle';for(const section of r.sections){const s=add('section','');add('h2',section.heading,s);for(const line of section.lines)add('p',line,s)}add('footer','Small steps. A growing world.');node.append(style,article);document.body.appendChild(node);document.title=r.title;window.addEventListener('afterprint',()=>{node.remove();document.title=old},{once:true});window.print()}
