import {languages} from './languages';
import {subjects,type SubjectId,type Snapshot} from './study';
import {topicTracks,type Topic} from './learning';
export type TopicDetail={topic_id:string;subject:SubjectId;title:string;custom:number;note:string;blocker:string;next_step:string;level:number;review_at:number|null;review_interval:number;review_count:number;last_reviewed:number|null;updated_at:number};
export type PracticeEntry={id:string;subject:SubjectId;topic_id:string|null;title:string;reflection:string;link:string;completed_at:number};
export type EvidenceFile={id:string;subject:SubjectId;topic_id:string|null;practice_id:string|null;filename:string;content_type:string;size:number;created_at:number};
export type WordReview={id:string;subject:SubjectId;count:number;created_at:number};
export type WeeklyReflection={week:string;helped:string;difficult:string;next:string;updated_at:number};
export type PlannerPreferences={dailyMinutes:number;busyMinutes:number;days:number[];priorities:SubjectId[]};
export type HorizonGoal={id:string;horizon:'week'|'month'|'six-months'|'year'|'five-years';title:string;done:boolean;created_at:number;completed_at:number|null};
export type JournalEntry={id:string;date:string;title:string;events:string;challenges:string;lessons:string;goals:string;vision:string;created_at:number;updated_at:number};
export type WorkspaceData={journal:JournalEntry[];horizonGoals:HorizonGoal[];topics:TopicDetail[];practice:PracticeEntry[];files:EvidenceFile[];wordReviews:WordReview[];wordReviewTotals:Partial<Record<SubjectId,number>>;reflections:WeeklyReflection[];preferences:PlannerPreferences;dayModes:{day:string;mode:'normal'|'busy'|'rest'}[]};
export const plannerDefaults:PlannerPreferences={dailyMinutes:45,busyMinutes:10,days:[1,2,3,4,5],priorities:['math','spanish','art']};
export const emptyWorkspace:WorkspaceData={journal:[],horizonGoals:[],topics:[],practice:[],files:[],wordReviews:[],wordReviewTotals:{},reflections:[],preferences:plannerDefaults,dayModes:[]};
export const understanding=['Not started','Studied','Can explain','Can apply','Can recall later'];
export function availableTopics(data:Snapshot): (Topic&{subject:SubjectId;custom?:boolean})[]{return [...Object.entries(topicTracks).flatMap(([subject,items])=>items.map(t=>({...t,subject:subject as SubjectId}))),...data.workspace.topics.filter(t=>t.custom).map(t=>({id:t.topic_id,title:t.title,subject:t.subject,custom:true,stage:'My topics',criterion:'Explore this topic in the way that matters to you.',reward:'Personal progress'}))]}
export function topicDetail(data:Snapshot,id:string):TopicDetail|undefined{return data.workspace.topics.find(t=>t.topic_id===id)}
export function topicLevel(data:Snapshot,id:string){return topicDetail(data,id)?.level??(data.topics.some(t=>t.topic_id===id&&t.learned)?2:0)}
export function localDay(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
export function weekKey(date=new Date()){const start=new Date(date);start.setDate(start.getDate()-(start.getDay()+6)%7);return localDay(start)}
export function studyPrompt(subject:SubjectId,title:string,note:string,blocker:string,level:number,nextStep=''){
return `Help me study ${subjects.find(s=>s.id===subject)?.name}: ${title}.\n\nWhat I want to understand more deeply:\n${note.trim()||'Help me identify the most useful questions about this topic.'}\n\nMy current understanding: ${understanding[level]??understanding[0]}.${blocker.trim()?`\nWhere I get stuck: ${blocker.trim()}`:''}${nextStep.trim()?`\nThe next step I want to work on: ${nextStep.trim()}`:''}\n\nFollow my interests above. Start by asking one focused question to check my starting point. Then teach one manageable step at a time, using concrete examples and practice. Let me attempt answers before showing solutions. Check my reasoning and help me explain the idea in my own words. At the end, suggest one small next step and something to revisit later.`;
}
const originalLanguageChallenges:Record<string,{title:string;task:string}[]>={spanish:[{title:'Spanish conversation starter',task:'Introduce yourself in Spanish and ask someone three questions. Record what felt natural and what you want to practice.'},{title:'Spanish reading explorer',task:'Read a short Spanish passage. Summarize its main idea and identify one phrase you can use.'},{title:'Spanish listening explorer',task:'Listen to a short Spanish clip twice. Write the main idea and check your interpretation against a transcript.'},{title:'Spanish writing explorer',task:'Write five connected sentences about your day. Check one grammar point and revise your draft.'}],german:[{title:'German conversation starter',task:'Introduce yourself in German and ask three questions. Note one sentence you would like to say more comfortably.'},{title:'German reading explorer',task:'Read a short German passage. Summarize it and identify the verb in three sentences.'},{title:'German listening explorer',task:'Listen to a short German clip. Compare your understanding with a transcript and revisit one difficult sentence.'},{title:'German writing explorer',task:'Write five connected sentences about your day. Check verb position and revise your draft.'}],latin:[{title:'Latin reading explorer',task:'Read a short Latin passage. Identify the subject and verb in three sentences.'},{title:'Latin translation explorer',task:'Translate a short passage. Explain how endings helped you work out each sentence.'},{title:'Latin grammar explorer',task:'Choose three nouns from a text. Identify their cases and explain what each one does in its sentence.'},{title:'Latin composition explorer',task:'Write three simple Latin sentences using forms you have studied. Check them against your reference and revise.'}]};

export const languageChallenges:Record<string,{title:string;task:string}[]>=Object.fromEntries(languages.map(l=>[l.id,originalLanguageChallenges[l.id]??[
{title:`${l.name} conversation`,task:`Introduce yourself in ${l.name} and ask three questions. Choose the variety you study; note one phrase to practice.`},
{title:`${l.name} reading`,task:`Read a short ${l.name} passage. Summarize it and identify three useful words or phrases.`},
{title:`${l.name} listening`,task:`Listen to a short ${l.name} recording. Compare your understanding with a transcript and revisit one sentence.`},
{title:`${l.name} writing`,task:`Write five connected sentences in ${l.name}. Pick one area to investigate: ${l.focus.toLowerCase()}. Use your reference to revise.`}
]]));
