import assert from 'node:assert/strict';
import {readAssistantPlanner,writeAssistantPlanner,readAssistantReply,writeAssistantReply,clearSentAssistantReply,clearCompletedAssistantDraft,clearBuiltAssistantPlanner} from '../src/lib/assistant-drafts';
const values=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value),removeItem:(key:string)=>values.delete(key)}});
const planner={title:'Practice a physics example',topic:'physics-units',minutes:25,track:true,preferences:{tone:'direct' as const,format:'paragraphs' as const,depth:'short' as const,style:'worked examples' as const,explanationLanguage:'English',variety:'',focus:[{area:'concepts' as const,topic:'units',level:'Beginner'}]}};
assert(writeAssistantPlanner('physics',{...planner,apiKey:'must not persist'} as any));
assert.deepEqual(readAssistantPlanner('physics'),planner);
assert(![...values.values()].some(value=>value.includes('must not persist')));
assert.equal(readAssistantPlanner('math'),null);
assert(writeAssistantPlanner('physics',{...planner,title:'Newer aim'}));
assert.equal(clearBuiltAssistantPlanner('physics',planner),false);
assert.equal(readAssistantPlanner('physics')?.title,'Newer aim');
assert(writeAssistantPlanner('physics',{...planner,preferences:{...planner.preferences,focus:[],explanationLanguage:''},minutes:0}));
assert.equal(readAssistantPlanner('physics')?.preferences.focus.length,0);
assert.equal(writeAssistantPlanner('physics',{...planner,title:'x'.repeat(181)}),false);
assert.equal(writeAssistantReply('lesson',{reply:'x'.repeat(5001),words:0}),false);
assert(writeAssistantReply('lesson',{reply:'First answer',words:10}));
assert(writeAssistantReply('lesson',{reply:'New answer during request',words:20}));
assert.equal(clearSentAssistantReply('lesson','First answer'),false);
assert.deepEqual(readAssistantReply('lesson'),{reply:'New answer during request',words:20});
assert(clearSentAssistantReply('lesson','New answer during request'));
assert.deepEqual(readAssistantReply('lesson'),{reply:'',words:20});
const captured={reply:'',words:20};
assert(writeAssistantReply('lesson',{reply:'',words:21}));
assert.equal(clearCompletedAssistantDraft('lesson',captured),false);
assert(clearCompletedAssistantDraft('lesson',{reply:'',words:21}));
assert.equal(readAssistantReply('lesson'),null);
values.set('atlas-assistant-draft-v1-reply-lesson','{"reply":"damaged"}');
assert.equal(readAssistantReply('lesson'),null);
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>{throw Error('unavailable')},setItem:()=>{throw Error('unavailable')},removeItem:()=>{throw Error('unavailable')}}});
assert.equal(readAssistantPlanner('physics'),null);
assert.equal(writeAssistantReply('lesson',{reply:'A draft',words:0}),false);
console.log('Passed: assistant drafts restore per subject/lesson, exclude unrelated fields, preserve newer answers and word counts after async completion, validate bounds, and tolerate unavailable storage.');
