import assert from 'node:assert/strict';
import {readHorizonDraft,writeHorizonDraft,clearHorizonDraft} from '../src/lib/horizon-goal-draft';
const items=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>items.get(key)??null,setItem:(key:string,value:string)=>items.set(key,value),removeItem:(key:string)=>items.delete(key)}});
assert(writeHorizonDraft('week','Study forces'));
assert(writeHorizonDraft('year','Speak German'));
assert.equal(readHorizonDraft('week'),'Study forces');
assert.equal(readHorizonDraft('year'),'Speak German');
assert.equal(writeHorizonDraft('week','x'.repeat(501)),false);
assert.equal(writeHorizonDraft('invalid' as any,'Invalid'),false);
assert(writeHorizonDraft('week','Study energy next'));
assert.equal(clearHorizonDraft('week','Study forces'),false);
assert.equal(readHorizonDraft('week'),'Study energy next');
assert(clearHorizonDraft('week','Study energy next'));
assert.equal(readHorizonDraft('week'),'');
assert.equal(readHorizonDraft('year'),'Speak German');
items.set('atlas-horizon-goal-draft-v1-month','x'.repeat(501));
assert.equal(readHorizonDraft('month'),'');
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>{throw Error('unavailable')},setItem:()=>{throw Error('unavailable')},removeItem:()=>{throw Error('unavailable')}}});
assert.equal(readHorizonDraft('week'),'');
assert.equal(writeHorizonDraft('week','A goal'),false);
console.log('Passed: horizon goal drafts remain separate, respect bounds, preserve newer text after async saving, and tolerate unavailable storage.');
