import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createJournalAutosave,journalEntries,type JournalDraft} from '../src/lib/journal-autosave';
import {blankState,transact,mutate,exportBackup} from '../src/lib/offline-store';
import {journalReport} from '../src/components/journal-editor';
import {reportHtml,wordBlob} from '../src/lib/reports';
import {weeklyReport} from '../src/components/weekly-progress';
import {registerCustomSubjects} from '../src/lib/study';
import {topicTracks} from '../src/lib/learning';
const draft:JournalDraft={id:randomUUID(),date:'2026-10-03',title:'Immediate navigation',events:'First words',challenges:'',lessons:'',goals:'',vision:''};
const latest={...draft,events:'The latest sentence before leaving Journal. 日本語'};
const writer=createJournalAutosave<JournalDraft>(async value=>{await transact(state=>mutate(state,{action:'journal-save',...value}))},10000);
writer.schedule(draft);
writer.schedule(latest);
// Leaving the editor cancels the pending debounce and flushes its latest draft.
writer.cancel();
await writer.flush(latest);
const backup=await exportBackup();
const savedJournal=backup.workspace.journal.filter(entry=>entry.id===draft.id);
assert.equal(savedJournal.length,1);
assert.equal(savedJournal[0].events,latest.events);
const blank={...draft,id:randomUUID(),title:'',events:''};
const all=journalEntries(savedJournal,blank);
assert.equal(all.length,1);
assert.equal(all[0].id,draft.id);
assert(!reportHtml(journalReport(all)).includes('2 saved entries'));
assert(reportHtml(journalReport(all)).includes(latest.events));
assert((await wordBlob(journalReport(all))).size>0);
const cleared={...blank,id:draft.id};
assert.equal(journalEntries(savedJournal,cleared).length,1);
assert.equal(journalEntries([],blank).length,0);
console.log('Passed: navigating before debounce saves the latest journal draft into a full backup; all-entry exports omit unsaved blank drafts and keep existing entries.');
const weekState=blankState(),start=new Date('2026-09-28T00:00:00').getTime(),customId=randomUUID(),subject=`custom-${customId}` as const;
mutate(weekState,{action:'subject-create',id:customId,name:'Music Theory'},start);
const customSession=randomUUID();
mutate(weekState,{action:'start',id:customSession,subject,seconds:1800},start+60000);
mutate(weekState,{action:'finish',id:customSession},start+31*60000);
const languageSession=randomUUID();
mutate(weekState,{action:'start',id:languageSession,subject:'japanese',seconds:600},start+35*60000);
mutate(weekState,{action:'finish',id:languageSession},start+45*60000);
const personalTopic=randomUUID();
mutate(weekState,{action:'topic-create',id:personalTopic,subject,title:'Read a chord chart',note:''},start+46*60000);
mutate(weekState,{action:'topic-update',topicId:personalTopic,learned:true},start+47*60000);
// Older backups can have learned built-in topics without a workspace note record.
const builtin=topicTracks.math[0];
weekState.data.topics.push({topic_id:builtin.id,subject:'math',learned:1,learned_at:start+48*60000});
weekState.data.topics.push({topic_id:topicTracks.math[1].id,subject:'math',learned:1,learned_at:start-1});
// Reports must use their snapshot's custom subjects even if the global list differs.
registerCustomSubjects([]);
const weekly=weeklyReport(weekState.data,'2026-09-28');
assert.deepEqual(weekly.sections.find(s=>s.heading==='Where I invested my time')!.lines,['Japanese: 10m','Music Theory: 30m']);
const accomplishments=weekly.sections.find(s=>s.heading==='What I accomplished')!.lines;
assert(accomplishments.includes(`Learned: ${builtin.title}`));
assert(accomplishments.includes('Learned: Read a chord chart'));
assert(!accomplishments.includes(`Learned: ${builtin.id}`));
assert(!accomplishments.includes(`Learned: ${topicTracks.math[1].title}`));
assert(weekly.sections[0].lines[0].startsWith('40m of focused study · 2 sessions'));
assert(reportHtml(weekly).includes('Music Theory: 30m'));
console.log('Passed: weekly reports include snapshot-specific custom subjects and languages, use catalog/personal topic titles, and exclude accomplishments outside the selected week.');
