import assert from 'node:assert/strict';
import {parseWeeklyDraft,writeWeeklyDraft,readWeeklyDraft,clearWeeklyDraft,rememberReflectionWeek,readReflectionWeek,withTargetRecord} from '../src/lib/weekly-reflection-draft';
import {defaultAssistant} from '../src/lib/assistant-schema';
import {blankState} from '../src/lib/offline-store';
import {studySearchEntries,parseSavedPlaces,validatePlaceTarget,recordRecentPlace,togglePinnedPlace,readSavedPlaces,availableSavedPlaces,savedPlacesKey,placeId} from '../src/lib/navigation-search';
const data=blankState().data;
data.workspace.journal.push({id:'journal-1',date:'2026-10-03',title:'A small win',events:'A unique memory about fractions',challenges:'',lessons:'',goals:'',vision:'',created_at:1,updated_at:1});
data.workspace.assistantLessons.push({id:'lesson-1',subject:'spanish',topic_id:null,session_id:null,title:'Reading about travel',minutes:15,provider:'deepseek',model:'test',preferences:defaultAssistant.preferences,messages:[{id:'message-1',role:'assistant',content:'Private conversation body',at:1}],created_at:1,updated_at:1,completed_at:null,request_id:null,requested_at:null});
data.workspace.practice.push({id:'practice-1',subject:'math',topic_id:null,title:'Fraction practice',reflection:'Explained thirds',link:'',completed_at:1});
data.workspace.horizonGoals.push({id:'horizon-1',horizon:'year',title:'Learn German',done:false,created_at:1,completed_at:null});
data.workspace.reflections.push({week:'2026-09-28',helped:'Daily reviews',difficult:'Finding time',next:'Smaller steps',updated_at:1});
const entries=studySearchEntries(data),journal=entries.find(e=>e.searchText.includes('unique memory'))!;
assert.deepEqual(journal.target,{tab:'journal',recordKind:'journal',recordId:'journal-1'});
assert.deepEqual(entries.find(e=>e.id==='practice-practice-1')!.target,{tab:'today',view:'gallery',subject:'math',recordKind:'practice',recordId:'practice-1'});
assert.deepEqual(entries.find(e=>e.id==='horizon-horizon-1')!.target,{tab:'goals',recordKind:'horizon',recordId:'horizon-1'});
assert.deepEqual(entries.find(e=>e.id==='weekly-2026-09-28')!.target,{tab:'progress',view:'weekly',recordKind:'weekly',recordId:'2026-09-28'});
assert.deepEqual(entries.find(e=>e.id==='lesson-lesson-1')!.target,{tab:'assistant',subject:'spanish',recordKind:'lesson',recordId:'lesson-1'});
assert(!entries.some(e=>e.searchText.includes('private conversation body')));
assert(entries.some(e=>e.kind==='Page'&&e.title==='Subjects'));
assert.equal(validatePlaceTarget({tab:'https://evil.example'}),null);
assert.equal(validatePlaceTarget({tab:'journal',recordId:'x\ninvalid'}),null);
assert.equal(validatePlaceTarget({tab:'subjects',subject:'unknown'}),null);
assert.deepEqual(validatePlaceTarget({tab:'assistant',apiKey:'secret',body:'private content'}),{tab:'assistant'});
assert.deepEqual(parseSavedPlaces('{broken'),{recent:[],pinned:[]});
assert.deepEqual(parseSavedPlaces(JSON.stringify({recent:[{title:'Bad target',kind:'Page',target:{tab:'malicious'},visitedAt:1}],pinned:[]})),{recent:[],pinned:[]});
const memory=new Map<string,string>();
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value),removeItem:(key:string)=>memory.delete(key)}});
Object.defineProperty(globalThis,'window',{configurable:true,value:new EventTarget()});
recordRecentPlace(journal.target,journal.title,journal.kind);
recordRecentPlace(journal.target,journal.title,journal.kind);
assert.equal(readSavedPlaces().recent.length,1);
assert(!memory.get(savedPlacesKey)!.includes('unique memory'));
for(let i=0;i<25;i++)recordRecentPlace({tab:'journal',recordKind:'journal',recordId:`entry-${i}`},`Entry ${i}`,'Journal');
assert.equal(readSavedPlaces().recent.length,12);
assert.equal(readSavedPlaces().recent[0].title,'Entry 24');
assert(togglePinnedPlace(journal.target,journal.title,journal.kind));
assert.equal(readSavedPlaces().pinned.length,1);
assert(togglePinnedPlace(journal.target,journal.title,journal.kind));
assert.equal(readSavedPlaces().pinned.length,0);
for(let i=0;i<20;i++)assert(togglePinnedPlace({tab:'journal',recordKind:'journal',recordId:`entry-${i}`},`Entry ${i}`,'Journal'));
assert.equal(togglePinnedPlace(journal.target,journal.title,journal.kind),false);
assert.equal(readSavedPlaces().pinned.length,20);
const current={id:placeId(journal.target),title:journal.title,kind:journal.kind,target:journal.target,visitedAt:1};
assert.deepEqual(availableSavedPlaces({recent:[current],pinned:[{...current,target:{tab:'journal',recordKind:'journal',recordId:'deleted-entry'},id:'deleted'}]},data),{recent:[current],pinned:[]});
console.log('Passed: search routes exact journal, practice, horizon goal and weekly records; favorites validate navigation-only fields, omit private bodies, bound storage, deduplicate recent visits and hide removed records.');

const reflection={week:'2026-09-28',helped:'Daily reviews',difficult:'Finding time',next:'Smaller steps'};
assert.deepEqual(parseWeeklyDraft(JSON.stringify({...reflection,apiKey:'never retain'})),reflection);
assert.equal(parseWeeklyDraft(JSON.stringify({...reflection,helped:'x'.repeat(2001)})),null);
assert.equal(parseWeeklyDraft(JSON.stringify({...reflection,week:'2026-09-29'})),null);
assert.equal(parseWeeklyDraft('{broken'),null);
assert(writeWeeklyDraft(reflection));
assert.deepEqual(readWeeklyDraft(),reflection);
const updated={...reflection,next:'An edit made during saving'};
assert(writeWeeklyDraft(updated));
clearWeeklyDraft(reflection);
assert.deepEqual(readWeeklyDraft(),updated);
clearWeeklyDraft(updated);
assert.equal(readWeeklyDraft(),null);
rememberReflectionWeek(reflection.week);
assert.equal(readReflectionWeek(),reflection.week);
assert.deepEqual(withTargetRecord([{id:'first'},{id:'second'},{id:'older'}],2,'older').map(i=>i.id),['older','first','second']);
assert.deepEqual(withTargetRecord([{id:'first'},{id:'second'}],2,'first').map(i=>i.id),['first','second']);
console.log('Passed: weekly drafts validate bounds, recover edits, preserve newer text during save, clear only the saved copy and remember the selected week; gallery includes exact older target records without duplicates.');

// Saving the complete form can clear an older partial local copy, while preserving later edits.
writeWeeklyDraft(reflection);
clearWeeklyDraft(updated,reflection);
assert.equal(readWeeklyDraft(),null);
writeWeeklyDraft(updated);
clearWeeklyDraft(reflection,reflection);
assert.deepEqual(readWeeklyDraft(),updated);
