import assert from 'node:assert/strict';
import {blankState} from '../src/lib/offline-store';
import {cleanNavigation,navigationHash,parseNavigationHash,validateNavigation} from '../src/lib/navigation';
import {availableTopics} from '../src/lib/workspace';
const data=blankState().data;
const topic=availableTopics(data)[0];
const route={tab:'subjects',subject:topic.subject,view:'learning',topicId:topic.id,minutes:25};
assert.deepEqual(parseNavigationHash(navigationHash(route)),route);
assert.deepEqual(cleanNavigation({tab:'learning',subject:'physics'}),{tab:'subjects',subject:'physics',view:'learning'});
assert.deepEqual(cleanNavigation({tab:'today',view:'weekly'}),{tab:'progress',view:'weekly'});
assert.equal(parseNavigationHash('#random'),null);
assert.equal(cleanNavigation({tab:'evil'}),null);
assert.deepEqual(cleanNavigation({tab:'assistant',apiKey:'secret',messages:'private',minutes:900,view:'malicious'}),{tab:'assistant'});
assert(!navigationHash({tab:'assistant',apiKey:'secret'} as any).includes('secret'));
assert.deepEqual(validateNavigation({tab:'subjects',subject:'removed' as any,topicId:'deleted',goalId:'deleted',recordKind:'journal',recordId:'deleted'},data),{tab:'subjects',subject:'math'});
assert.equal(validateNavigation(route,data).topicId,topic.id);
data.customSubjects.push({id:'custom-check',name:'Music',color:'#c8a5ff',glyph:'♪'} as any);
assert.equal(validateNavigation({tab:'subjects',subject:'custom-check' as any},data).subject,'custom-check');
console.log('Passed: file-compatible navigation hash round trips, legacy paths migrate, unknown route settings/credentials are excluded, and stale targets fall back safely.');
