import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {recoverPracticeDraft,flushPracticeDraft,type PracticeDraft} from '../src/lib/practice-draft';
import {practiceBanks,numericAnswer,checkExercise} from '../src/lib/practice';
import type {ExerciseAttempt} from '../src/lib/practice-types';
const bank=practiceBanks['math-whole-number-operations'],exercise=bank.exercises.find(e=>e.format==='number'&&e.purpose==='guided')!;
const draft:PracticeDraft={attemptId:randomUUID(),answer:'257',reflection:'My own method',hintCount:1,solutionRevealed:false,expectedUpdatedAt:null};
assert.deepEqual(recoverPracticeDraft(JSON.parse(JSON.stringify(draft)),exercise,[],randomUUID)?.draft,draft,'Generated attempt IDs and unsaved work must survive JSON recovery.');
for(const invalid of [{...draft,attemptId:'bad'},{...draft,answer:'x'.repeat(5001)},{...draft,hintCount:100},{...draft,expectedUpdatedAt:-1}])assert.equal(recoverPracticeDraft(invalid,exercise,[],randomUUID),null);
const saved:ExerciseAttempt={id:draft.attemptId,topic_id:bank.topicId,exercise_id:exercise.id,content_version:bank.version,answer:'256',reflection:'Submitted elsewhere',hint_count:2,solution_revealed:true,status:'incorrect',created_at:1,updated_at:3,review_at:86400003,submitted_at:2,hint_count_on_submit:0,solution_on_submit:false};
const savedCopy=structuredClone(saved),recovered=recoverPracticeDraft(draft,exercise,[saved],randomUUID)!;
assert.equal(recovered.recovered,true);assert.notEqual(recovered.draft.attemptId,saved.id);assert.equal(recovered.draft.expectedUpdatedAt,null);assert.equal(recovered.draft.answer,draft.answer);assert.equal(recovered.draft.reflection,draft.reflection);assert.deepEqual(saved,savedCopy,'Recovery must preserve the immutable submitted record.');
assert.deepEqual(recoverPracticeDraft(recovered.draft,exercise,[saved],randomUUID)?.draft,recovered.draft,'Saving the recovered draft must stabilize its new attempt identity.');
const matching={...draft,answer:saved.answer,reflection:saved.reflection};
const canonical=recoverPracticeDraft(matching,exercise,[saved],randomUUID)!;
assert.equal(canonical.recovered,false);assert.equal(canonical.draft.hintCount,2);assert.equal(canonical.draft.solutionRevealed,true);assert.equal(canonical.draft.expectedUpdatedAt,3);
for(const answer of ['1/1e309','0/1e309','1e309/1','1/0','0/0'])assert.equal(numericAnswer(answer),null);
assert.equal(numericAnswer('1/1e300'),1e-300);assert.equal(numericAnswer('3/4'),0.75);
const zero=Object.values(practiceBanks).flatMap(b=>b.exercises).find(e=>e.format==='number'&&e.answer===0)!;
assert.equal(checkExercise(zero,'1/1e309').status,'incorrect');assert.equal(checkExercise(zero,'0').status,'correct');
let left=false,saves=0;
await assert.rejects(async()=>{await flushPracticeDraft(true,async()=>{saves++;return false});left=true},/has not saved/);
assert.equal(left,false,'A failed durable save must block navigation even when browser recovery is unavailable.');
await flushPracticeDraft(true,async()=>{saves++;return true});left=true;assert.equal(left,true);assert.equal(saves,2);
await flushPracticeDraft(false,async()=>{throw new Error('Clean work must not save again')});
console.log('Passed: generated draft IDs recover, divergent cached work preserves both attempts, help stays monotonic, failed saves block navigation, and nonfinite fraction operands are rejected.');
