import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import JSZip from 'jszip';
import {blankState,mutate,settle,transact,mergeBackup,exportBackup,addFile} from '../src/lib/offline-store';
import {languages} from '../src/lib/languages';
import {vocabularyTracks} from '../src/lib/learning';
import {base64} from '../src/lib/files';
import {subjects} from '../src/lib/study';
import {backupSchema} from '../src/lib/backup';
import {wordBlob,reportHtml,markdown,plainText} from '../src/lib/reports';
const command=(s:ReturnType<typeof blankState>,c:unknown,t=1000)=>mutate(s,c,t);
const makeBackup=(s:ReturnType<typeof blankState>)=>({format:'atlas-study-backup',version:2,...s.data,wordEntries:s.wordEntries,fileData:[]});
let s=blankState(),id=randomUUID();command(s,{action:'start',id,subject:'physics',seconds:60});command(s,{action:'pause',id},21000);command(s,{action:'resume',id},121000);command(s,{action:'finish',id},131000);assert.equal(s.data.totals.physics,30000);command(s,{action:'finish',id},200000);assert.equal(s.data.totals.physics,30000);
s=blankState();id=randomUUID();command(s,{action:'start',id,subject:'math',seconds:60});settle(s,500000);assert.equal(s.data.totals.math,60000);assert.equal(s.data.sessions[0].ended_at,61000);
s=blankState();const wordId=randomUUID();command(s,{action:'words-add',id:wordId,subject:'latin',count:100});command(s,{action:'words-add',id:wordId,subject:'latin',count:100});command(s,{action:'words-add',id:randomUUID(),subject:'japanese',count:25});assert.equal(s.data.wordCounts.latin,100);assert.equal(s.data.wordCounts.japanese,25);assert.deepEqual(vocabularyTracks.latin.filter(m=>m.count>100).slice(0,5).map(m=>m.count),[150,200,250,300,350]);
command(s,{action:'words-review',id:randomUUID(),subject:'latin',count:50});assert.equal(s.data.wordCounts.latin,100);assert.equal(s.data.workspace.wordReviewTotals.latin,50);command(s,{action:'words-set',subject:'latin',count:10});assert(s.data.badges.some(b=>b.badge_id==='words-latin-100'));
for(const l of languages)command(s,{action:'words-set',subject:l.id,count:50000});assert(s.data.badges.length>12000);assert.equal(backupSchema.safeParse(makeBackup(s)).success,true);const imported=blankState();mergeBackup(imported,makeBackup(s));assert.equal(imported.data.wordCounts.japanese,50000);assert.equal(imported.data.badges.length,s.data.badges.length);
command(s,{action:'words-set',subject:'spanish',count:1000000});assert.throws(()=>command(s,{action:'words-add',id:randomUUID(),subject:'spanish',count:1}));assert.throws(()=>command(s,{action:'goal-create',id:randomUUID(),subject:'math',title:'Impossible date',reason:'',targetDate:'2026-02-30',steps:[]}));
s=blankState();const custom=randomUUID(),subject=`custom-${custom}` as const,topic=randomUUID();command(s,{action:'subject-create',id:custom,name:'Music Theory'});command(s,{action:'topic-create',id:topic,subject,title:'Read a chord chart',note:'Understand chord inversions'});command(s,{action:'topic-level',topicId:topic,level:2});assert(s.data.badges.some(b=>b.badge_id===`topic-${topic}`));const goal=randomUUID();command(s,{action:'goal-create',id:goal,subject,title:'Play three songs',reason:'',targetDate:'',steps:[]});command(s,{action:'goal-update',id:goal,completed:true,steps:[]},2000);assert(s.data.badges.some(b=>b.badge_id===`goal-${subject}-1`));const h=randomUUID();command(s,{action:'horizon-goal-add',id:h,horizon:'five-years',title:'Compose an album'});command(s,{action:'horizon-goal-update',id:h,done:true});const j=randomUUID();command(s,{action:'journal-save',id:j,date:'2026-10-03',title:'今日の勉強',events:'Aprendí más',challenges:'A difficult chord',lessons:'Smaller steps helped',goals:'Practice',vision:'Compose'});const round=blankState();mergeBackup(round,makeBackup(s));assert.equal(round.data.workspace.journal[0].title,'今日の勉強');assert.equal(round.data.workspace.horizonGoals[0].title,'Compose an album');assert.equal(round.data.customSubjects[0].name,'Music Theory');mergeBackup(round,makeBackup(s));assert.equal(round.data.workspace.journal.length,1);assert.equal(round.data.goals.length,1);
const bad=structuredClone(makeBackup(s));bad.sessions.push({id:randomUUID(),subject:'math',goal_id:goal,topic_id:null,status:'stopped',planned_seconds:60,accumulated_ms:1,credited_ms:1,running_since:null,started_at:1000,ended_at:2000,note:''});assert.throws(()=>mergeBackup(blankState(),bad));
await Promise.all(Array.from({length:20},()=>transact(s=>mutate(s,{action:'words-add',id:randomUUID(),subject:'german',count:10}))));assert.equal((await transact(s=>s.data,false)).wordCounts.german,200);await assert.rejects(transact(s=>{s.data.wordCounts.german=999;throw Error('rollback')}));assert.equal((await transact(s=>s.data,false)).wordCounts.german,200);
const concurrentCustom=randomUUID();await Promise.allSettled([transact(s=>mutate(s,{action:'subject-create',id:concurrentCustom,name:'Drawing ideas'})),transact(()=>{throw Error('expected failure')})]);assert(subjects.some(s=>s.id===`custom-${concurrentCustom}`));
const bytes=new TextEncoder().encode('A useful study note. 中文'),file={id:randomUUID(),subject:'math' as const,topic_id:null,practice_id:null,filename:'note.txt',content_type:'text/plain',size:bytes.length,created_at:Date.now()};await transact(s=>addFile(s,file,bytes));const b=await exportBackup();assert.equal(b.fileData[0].data,base64(bytes));const withFile=blankState();mergeBackup(withFile,b);assert.equal(await withFile.fileData[file.id].text(),'A useful study note. 中文');assert.throws(()=>addFile(withFile,{...file,id:randomUUID(),filename:'unsafe.svg',content_type:'image/svg+xml'},new TextEncoder().encode('<svg/>')));
const corrupt=structuredClone(b);corrupt.fileData[0].size++;await assert.rejects(transact(s=>mergeBackup(s,corrupt)));assert.equal((await transact(s=>s.data,false)).workspace.files.length,1);
const report={title:'Study <script>alert(1)</script>',subtitle:'English · 日本語',sections:[{heading:'Challenges',lines:['A & B','今日の勉強']} ]};assert(reportHtml(report).includes('&lt;script&gt;'));assert(markdown(report).includes('今日の勉強'));assert(plainText(report).includes('A & B'));const zip=await JSZip.loadAsync(await (await wordBlob(report)).arrayBuffer()),xml=await zip.file('word/document.xml')!.async('string');assert(xml.includes('今日の勉強'));assert(xml.includes('A &amp; B'));
console.log('Passed: timer caps and pauses; per-language counts and 50k milestones; 50-language backup round-trip; corrections keep badges; custom subjects/topic/quest achievements; goal horizons and Unicode journals; concurrent IDB writes and rollback; attachment backup safety; valid Word/Markdown/text/print exports.');

// Lesson checks use the catalog answer; every existing topic has an offline explanation.
const {studyLessons}=await import('../src/lib/study-lessons');
const {topicTracks}=await import('../src/lib/learning');
assert.deepEqual(Object.keys(studyLessons).sort(),Object.values(topicTracks).flat().map(t=>t.id).sort());
for(const [id,l]of Object.entries(studyLessons)){assert.equal(l.choices.length,3);assert(l.answer>=0&&l.answer<3);assert(l.explanation.length>=1);assert(l.example.length>20);assert(l.question.length>10);assert(l.terms.every(t=>t.term&&t.definition));assert(l.sources.every(s=>new URL(s.url).protocol==='https:'));}
s=blankState();const builtId=Object.keys(studyLessons)[0],l=studyLessons[builtId],practiceId=randomUUID();assert.throws(()=>command(s,{action:'lesson-complete',topicId:builtId,answer:(l.answer+1)%3,canExplain:true,practiceId}));assert.equal(s.data.workspace.lessonCompletions.length,0);command(s,{action:'lesson-complete',topicId:builtId,answer:l.answer,canExplain:true,practiceId});command(s,{action:'lesson-complete',topicId:builtId,answer:l.answer,canExplain:true,practiceId:randomUUID()});assert.equal(s.data.workspace.practice.length,1);assert(s.data.badges.some(b=>b.badge_id===`topic-${builtId}`));assert.equal(s.data.topics.find(t=>t.topic_id===builtId)?.learned,1);
const {defaultAssistant}=await import('../src/lib/assistant-schema');
const {requestBody,responseText,askAssistant,lessonInstructions}=await import('../src/lib/assistant');
const lesson={id:randomUUID(),subject:'japanese' as const,topic_id:null,session_id:null,title:'Reading about food',minutes:25,provider:'openai' as const,model:'gpt-6-astra',preferences:{...defaultAssistant.preferences,focus:[{area:'reading' as const,topic:'Food',level:'A1 · Beginner'}]},messages:[{id:randomUUID(),role:'user' as const,content:'Help me read about food.',at:1000}],created_at:1000,updated_at:1000,completed_at:null,request_id:null,requested_at:null};
command(s,{action:'assistant-save',lesson,expectedLastMessageId:null,requestId:randomUUID(),claim:true});assert.throws(()=>command(s,{action:'assistant-save',lesson,expectedLastMessageId:null}));const activeRequest=s.data.workspace.assistantLessons[0].request_id!;assert.throws(()=>command(s,{action:'assistant-save',lesson,expectedLastMessageId:lesson.messages[0].id,requestId:randomUUID(),claim:true}));const answered={...lesson,messages:[...lesson.messages,{id:randomUUID(),role:'assistant' as const,content:'Here is a short reading passage.',at:2000}]};command(s,{action:'assistant-save',lesson:answered,expectedLastMessageId:lesson.messages[0].id,requestId:activeRequest},2000);assert.equal(s.data.workspace.assistantLessons[0].request_id,null);
const unrelatedTimer=randomUUID();command(s,{action:'start',id:unrelatedTimer,subject:'japanese',seconds:60},2000);assert.throws(()=>command(s,{action:'assistant-timer',id:lesson.id,sessionId:randomUUID()},3000));command(s,{action:'finish',id:unrelatedTimer},4000);const assistantTimer=randomUUID();command(s,{action:'assistant-timer',id:lesson.id,sessionId:assistantTimer},5000);command(s,{action:'pause',id:assistantTimer},15000);command(s,{action:'assistant-finish',id:lesson.id,wordCount:10},90000);command(s,{action:'assistant-finish',id:lesson.id,wordCount:10},190000);assert.equal(s.data.wordCounts.japanese,10);assert.equal(s.data.sessions.find(t=>t.id===assistantTimer)?.credited_ms,10000);assert.equal(s.data.workspace.practice.filter(p=>p.id===lesson.id).length,1);assert.equal(s.data.workspace.topics.find(t=>t.topic_id===lesson.id)?.level,1);assert(!s.data.badges.some(b=>b.badge_id===`topic-${lesson.id}`));const aiRound=blankState();mergeBackup(aiRound,makeBackup(s));assert.equal(aiRound.data.workspace.assistantLessons[0].messages.length,2);assert.equal(aiRound.data.workspace.lessonCompletions.length,1);
assert.equal(responseText('openai',{output:[{type:'reasoning',summary:[]},{type:'message',content:[{type:'output_text',text:'One'}]},{type:'message',content:[{type:'output_text',text:'Two'}]}]}),'One\nTwo');assert.equal(responseText('claude',{content:[{type:'text',text:'Bonjour'}]}),'Bonjour');assert.equal(responseText('deepseek',{choices:[{message:{content:'你好'}}]}),'你好');assert.equal((requestBody('openai','m','i',lesson.messages) as any).store,false);assert(lessonInstructions(lesson,s.data).includes('Japanese'));assert(!lessonInstructions(lesson,s.data).includes('A difficult chord'));
let requests=0;await assert.rejects(askAssistant({...defaultAssistant,enabled:false},'secret',lesson,s.data,new AbortController().signal,async()=>{requests++;return Response.json({})}));assert.equal(requests,0);const fakeKey='testing-key-only';const text=await askAssistant({...defaultAssistant,enabled:true},' '+fakeKey+' ',lesson,s.data,new AbortController().signal,async(url,opts)=>{requests++;assert.equal(url,'https://api.openai.com/v1/responses');assert.equal((opts?.headers as any).Authorization,`Bearer ${fakeKey}`);assert(!opts?.body?.toString().includes(fakeKey));return Response.json({output:[{type:'message',content:[{type:'output_text',text:'Mock lesson'}]}]});});assert.equal(text,'Mock lesson');assert(!JSON.stringify(makeBackup(s)).includes(fakeKey));await assert.rejects(askAssistant({...defaultAssistant,enabled:true},fakeKey,lesson,s.data,new AbortController().signal,async()=>Response.json({error:{message:fakeKey}},{status:401})),e=>e instanceof Error&&!e.message.includes(fakeKey));
const oldFormat=makeBackup(blankState()) as any;delete oldFormat.workspace.assistantLessons;delete oldFormat.workspace.lessonCompletions;delete oldFormat.workspace.journal;delete oldFormat.workspace.horizonGoals;delete oldFormat.customSubjects;const restoredHosted=blankState();mergeBackup(restoredHosted,oldFormat);assert.equal(restoredHosted.data.sessionCount,0);
console.log('Passed: all 96 offline lessons; meaningful checks and automatic topic rewards; assistant concurrent-save guards, request locks and idempotent completion; separate lesson timers, pause exclusion, per-language words; full backup round-trip; provider shapes and mocked calls; disabled AI makes no requests; errors and backups exclude API keys; existing hosted backup imports.');

const savedReply=await askAssistant({...defaultAssistant,enabled:true,connection:'companion'},'',lesson,s.data,new AbortController().signal,async(url,opts)=>{assert.equal(url,'http://127.0.0.1:5175/api/assistant');const payload=JSON.parse(String(opts?.body));assert.equal(payload.useSavedKey,true);assert(!Object.hasOwn(payload,'key'));assert(!JSON.stringify(payload).includes(fakeKey));return Response.json({output:[{type:'message',content:[{type:'output_text',text:'Saved-key mock lesson'}]}]});});assert.equal(savedReply,'Saved-key mock lesson');
await assert.rejects(askAssistant({...defaultAssistant,enabled:true,connection:'direct'},'',lesson,s.data,new AbortController().signal,async()=>{throw Error('Must not call direct without key')}),/Enter your provider API key/);
const {credentialAction}=await import('../src/lib/assistant');
Object.defineProperty(globalThis,'location',{value:{origin:'https://example.com'},configurable:true});
let vaultCalls=0;await assert.rejects(credentialAction('status','deepseek',undefined,async()=>{vaultCalls++;return Response.json({})}),/local companion/);assert.equal(vaultCalls,0);
Object.defineProperty(globalThis,'location',{value:{origin:'http://127.0.0.1:5175'},configurable:true});
const vaultStatus=await credentialAction('status','deepseek',undefined,async(url,opts)=>{assert.equal(url,'/api/credentials');assert.deepEqual(JSON.parse(String(opts?.body)),{action:'status',provider:'deepseek'});return Response.json({supported:true,storeName:'macOS Keychain',saved:true});});assert.equal(vaultStatus.saved,true);
await assert.rejects(credentialAction('save','deepseek',fakeKey,async()=>Response.json({error:fakeKey},{status:500})),e=>e instanceof Error&&!e.message.includes(fakeKey));
console.log('Saved-key browser request isolation checks passed.');

const fileReply=await askAssistant({...defaultAssistant,enabled:true,connection:'companion',keySource:'file',allowKeyFile:true},'',lesson,s.data,new AbortController().signal,async(url,opts)=>{assert.equal(url,'http://127.0.0.1:5175/api/assistant');const payload=JSON.parse(String(opts?.body));assert.equal(payload.useKeyFile,true);assert.equal(payload.allowKeyFile,true);assert(!Object.hasOwn(payload,'key'));assert(!Object.hasOwn(payload,'useSavedKey'));return Response.json({output:[{type:'message',content:[{type:'output_text',text:'Local-file mock lesson'}]}]});});assert.equal(fileReply,'Local-file mock lesson');
let fileDeniedCalls=0;await assert.rejects(()=>askAssistant({...defaultAssistant,enabled:true,connection:'companion',keySource:'file',allowKeyFile:false},'',lesson,s.data,new AbortController().signal,async()=>{fileDeniedCalls++;throw Error('Must not call')}),/Enable local key-file access/);assert.equal(fileDeniedCalls,0);
console.log('Passed: explicit local key-file source request excludes key and vault fallback; denied access makes no request.');
