import {useState} from 'react';
import {Plus,Download,Printer,Check,Target} from 'lucide-react';
import {toast} from 'sonner';
import {Checkbox} from './ui/checkbox';
import {type Snapshot} from '@/lib/study';
import {type HorizonGoal} from '@/lib/workspace';
import {downloadReport,printReport,type Report} from '@/lib/reports';
export const horizons=[['week','This week'],['month','This month'],['six-months','Next 6 months'],['year','Next year'],['five-years','Next 5 years']] as const;
export function goalReport(data:Snapshot):Report{return {title:'My goals & vision',subtitle:new Date().toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'}),sections:horizons.map(([id,label])=>({heading:label,lines:data.workspace.horizonGoals.filter(g=>g.horizon===id).map(g=>`${g.done?'✓':'□'} ${g.title}`)})).map(s=>({...s,lines:s.lines.length?s.lines:['Space for my next goal.']}))}}
export default function GoalBoard({data,act,pending}:{data:Snapshot;act:(c:Record<string,unknown>)=>Promise<Snapshot>;pending:boolean}){const [horizon,setHorizon]=useState<HorizonGoal['horizon']>('week'),[title,setTitle]=useState(''),[adding,setAdding]=useState(false);return <section className="goal-board"><div className="section-title"><div><p className="eyebrow">Short steps · Long vision</p><h2>Your goal horizons</h2><p className="muted">Keep what you want to achieve visible.</p></div><div className="action-row"><button className="secondary-button" onClick={()=>void downloadReport(goalReport(data),'html','atlas-goals')}><Download size={16}/> Download goal poster</button><button className="secondary-button" onClick={()=>printReport(goalReport(data))}><Printer size={16}/> Print / Save PDF</button></div></div><form className="panel horizon-add" onSubmit={async e=>{e.preventDefault();setAdding(true);try{await act({action:'horizon-goal-add',id:crypto.randomUUID(),horizon,title});setTitle('')}catch{}finally{setAdding(false)}}}><label>Time horizon<select aria-label="Goal time horizon" value={horizon} onChange={e=>setHorizon(e.target.value as HorizonGoal['horizon'])}>{horizons.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>What I want to achieve<textarea required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Describe the goal or vision you want to keep in sight."/></label><button className="primary-button" disabled={pending||adding}><Plus size={16}/> Add to my board</button></form><div className="horizon-grid">{horizons.map(([id,label])=><section className="panel horizon-card" key={id}><p className="eyebrow">{label}</p><Target size={24}/>{data.workspace.horizonGoals.filter(g=>g.horizon===id).map(g=><label className={'horizon-item '+(g.done?'done':'')} key={g.id}><Checkbox aria-label={`Complete ${g.title}`} checked={g.done} disabled={pending} onCheckedChange={done=>void act({action:'horizon-goal-update',id:g.id,done:done===true}).catch(()=>{})}/><span>{g.title}{g.completed_at&&<small>Completed {new Date(g.completed_at).toLocaleDateString()}</small>}</span></label>)}{!data.workspace.horizonGoals.some(g=>g.horizon===id)&&<p className="muted">What would you love to achieve?</p>}</section>)}</div></section>}
