import {useState} from 'react';
import {toast} from 'sonner';
import type {AssistantConfig,Provider} from '@/lib/assistant-schema';
import {isLocalCompanion,keyFileAction,type KeyFileStatus} from '@/lib/assistant';
export default function KeyFileSettings({config,status,onConfig,onStatus}:{config:AssistantConfig;status?:KeyFileStatus;onConfig:(c:AssistantConfig)=>void;onStatus:(provider:Provider,status:KeyFileStatus)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const allowed=config.allowKeyFile===true&&config.connection==='companion'&&isLocalCompanion();
 const manage=async(action:'status'|'create-template'|'clear')=>{setBusy(true);setError('');try{const next=await keyFileAction(action,config.provider,allowed);onStatus(config.provider,next);if(action!=='status')toast.success(action==='clear'?'Key cleared from local file':'Local key file ready',{description:action==='clear'?'The selected provider entry is empty. Other provider keys are kept. Revocation happens in your provider account.':'An existing file is kept as it is. Fill in the selected provider entry, then check the file status.'})}catch(e){setError(e instanceof Error?e.message:'The local key file could not be accessed.')}finally{setBusy(false)}};
 return <section className="credential-panel"><h4>Optional local API-key file</h4><p className="small-note">This JSON file contains readable text. Use your computer’s credential store if you prefer protected storage. Never upload a filled key file to GitHub or share it.</p><label className="check-row"><input aria-label="Allow local key-file access" type="checkbox" checked={config.allowKeyFile===true} disabled={busy||!isLocalCompanion()||config.connection!=='companion'} onChange={e=>{onConfig({...config,allowKeyFile:e.target.checked,keySource:e.target.checked?config.keySource:'vault'});setError('')}}/>Allow local key-file access</label><label>Key source when this tab’s key is empty<select aria-label="Companion API-key source" value={config.keySource??'vault'} disabled={busy||config.connection!=='companion'} onChange={e=>onConfig({...config,keySource:e.target.value as 'vault'|'file'})}><option value="vault">Computer credential store</option><option value="file" disabled={!allowed}>Local API-key file</option></select></label>{allowed&&<><p className="small-note">{status?status.saved?'A key is present for this provider.':'No key for this provider in the file.':'File status is unavailable. Click Check file status to retry.'}</p>{status&&<label>Local key file location<input aria-label="Local key file location" readOnly value={status.filePath}/></label>}<div className="report-actions"><button type="button" className="secondary-button" disabled={busy} onClick={()=>void manage('create-template')}>Create empty template</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>void manage('status')}>Check file status</button><button type="button" className="secondary-button" disabled={busy||!status?.saved} onClick={()=>void manage('clear')}>Clear selected key from file</button></div><p className="small-note">Open the file in a text editor. Enter your key inside the quotes after “{config.provider}”, save the file, and check its status. Clearing empties that entry. Turning file access off stops reads and keeps the file intact. A typed tab key takes priority.</p></>}{!isLocalCompanion()&&<p className="small-note">Open the included local companion to use a key file.</p>}{error&&<p role="alert" className="small-note">{error}</p>}</section>;
}
