import {topicDifficulty} from '@/lib/difficulty';
import {useRef,useState} from 'react';
import {Tooltip} from 'radix-ui';
import {BookOpen,CheckCircle2,HelpCircle} from 'lucide-react';
import {toast} from 'sonner';
import {studyLessons,type StudyLesson} from '@/lib/study-lessons';
import type {Snapshot} from '@/lib/study';
function Term({term,definition}:{term:string;definition:string}){const [open,setOpen]=useState(false);return <Tooltip.Root open={open} onOpenChange={setOpen}><Tooltip.Trigger asChild><button type="button" className="lesson-term" onClick={()=>setOpen(!open)} aria-label={`${term}: definition`}>{term}</button></Tooltip.Trigger><Tooltip.Portal><Tooltip.Content className="term-popup" side="top" sideOffset={8} collisionPadding={16}><strong>{term}</strong><p>{definition}</p><Tooltip.Arrow/></Tooltip.Content></Tooltip.Portal></Tooltip.Root>}
function explain(text:string,lesson:StudyLesson){const terms=lesson.terms.filter(t=>t.term.trim()).sort((a,b)=>b.term.length-a.term.length);if(!terms.length)return text;const escape=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const regex=new RegExp(`(?<![\\p{L}\\p{N}_])(${terms.map(t=>escape(t.term)).join('|')})(?![\\p{L}\\p{N}_])`,'giu');return text.split(regex).map((part,i)=>{const term=terms.find(t=>t.term.toLowerCase()===part.toLowerCase());return term?<Term key={i} term={part} definition={term.definition}/>:part})}
export default function LessonReader({id,data,pending,act}:{id:string;data:Snapshot;pending:boolean;act:(c:Record<string,unknown>)=>Promise<Snapshot>}){const lesson=studyLessons[id],done=data.workspace.lessonCompletions.some(l=>l.topic_id===id),[answer,setAnswer]=useState<number|null>(null),[checked,setChecked]=useState(false),[canExplain,setCanExplain]=useState(false);const practiceId=useRef(crypto.randomUUID());if(!lesson)return null;const correct=answer===lesson.answer;const finish=async()=>{try{await act({action:'lesson-complete',topicId:id,answer,canExplain:true,practiceId:practiceId.current});toast.success('Lesson complete',{description:'Your topic, practice record, review queue, and earned rewards have updated.'})}catch{}};
return <Tooltip.Provider delayDuration={250}><section className="studio-section built-in-lesson"><p className="eyebrow"><BookOpen size={15}/> Learn this topic · Works offline</p><span className="difficulty-label">{topicDifficulty(id)}</span><h2>{lesson.title}</h2><p className="small-note">Highlighted terms open a definition when you hover, tap, or focus them.</p>{lesson.explanation.map((p,i)=><p className="lesson-paragraph" key={i}>{explain(p,lesson)}</p>)}<div className="lesson-example"><h3>A concrete example</h3><p>{explain(lesson.example,lesson)}</p>{lesson.analogy&&<p>{explain(lesson.analogy,lesson)}</p>}</div><details className="lesson-glossary"><summary><HelpCircle size={15}/> Terms explained</summary><dl>{lesson.terms.map(t=><div key={t.term}><dt>{t.term}</dt><dd>{t.definition}</dd></div>)}</dl></details><div className="lesson-check"><h3>Check your understanding</h3><p>{lesson.question}</p><fieldset><legend className="sr-only">Choose an answer</legend>{lesson.choices.map((choice,index)=><label className={'lesson-choice '+(answer===index?'selected':'')} key={choice}><input type="radio" name={'lesson-'+id} checked={answer===index} onChange={()=>{setAnswer(index);setChecked(false)}}/>{choice}</label>)}</fieldset><button type="button" className="secondary-button" disabled={answer===null} onClick={()=>setChecked(true)}>Check answer</button>{checked&&<p role="status" className={correct?'lesson-correct':'lesson-retry'}>{correct?lesson.feedback:'Try again. Revisit the example, then choose the answer that fits it.'}</p>}<p className="lesson-practice"><strong>Try it yourself:</strong> {lesson.practice}</p>{done?<p className="lesson-completed"><CheckCircle2 size={18}/> Lesson completed and saved</p>:<><label className="check-row"><input type="checkbox" checked={canExplain} onChange={e=>setCanExplain(e.target.checked)}/> I can explain this idea in my own words.</label><button className="primary-button" disabled={pending||!checked||!correct||!canExplain} onClick={()=>void finish()}>Complete lesson & collect rewards</button><p className="small-note">A correct answer and your explanation check mark the topic as learned. Study hours come from your focus timer.</p></>}</div><details><summary>References for further study</summary><ul>{lesson.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} ↗</a></li>)}</ul><p className="small-note">Reference links need internet. This lesson is included in Atlas.</p></details></section></Tooltip.Provider>}
