import {useEffect,useRef,useState} from 'react';
import {BookOpen,Clock,FileText,Play,Plus,Sparkles,Trophy,ArrowRight} from 'lucide-react';
import {toast} from 'sonner';
import SubjectPicker from './subject-picker';
import LearningPath from './learning-path';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './ui/tabs';
import {Progress} from './ui/progress';
import {allAwards} from '@/lib/learning';
import {isLanguage} from '@/lib/languages';
import {subjects,formatTime,levelFor,type SubjectId,type Snapshot} from '@/lib/study';
import {availableTopics,topicDetail,topicLevel,understanding,languageChallenges} from '@/lib/workspace';
import {topicDifficulty} from '@/lib/difficulty';
import {practiceBanks,practiceEvidence} from '@/lib/practice';
import type {NavigationTarget} from '@/lib/navigation';

type Props={data:Snapshot;selected:SubjectId;choose:(id:SubjectId)=>void;act:(command:Record<string,unknown>)=>Promise<Snapshot>;pending:boolean;loaded:boolean;onOpenTopic:(id:string)=>void;onStudy:(subject:SubjectId,topicId:string|null,minutes:number,goalId?:string)=>void;onAssistant:(subject:SubjectId,topicId?:string)=>void;onNavigate:(target:NavigationTarget)=>void;view:string;onView:(view:string)=>void};
const sectionNames=['overview','learning','notes','practice','rewards'];
export default function SubjectHub(props:Props){
 const {data,selected,choose,act,pending,loaded,onOpenTopic,onStudy,onAssistant,onNavigate,view,onView}=props;
 const subject=subjects.find(s=>s.id===selected)??subjects[0],topics=availableTopics(data).filter(t=>t.subject===selected),studied=data.totals[selected]??0,level=levelFor(studied),language=isLanguage(selected);
 const learned=topics.filter(t=>data.topics.some(p=>p.topic_id===t.id&&p.learned)).length;
 const awards=allAwards(data).filter(a=>a.subject===selected),earned=awards.filter(a=>data.badges.some(b=>b.badge_id===a.id)),upcoming=awards.filter(a=>!data.badges.some(b=>b.badge_id===a.id));
 const nextWords=upcoming.find(a=>a.kind==='words'),nextTime=upcoming.find(a=>a.kind==='time');
 const nextTopic=topics.find(t=>!data.topics.some(p=>p.topic_id===t.id&&p.learned)),notes=topics.filter(t=>{const note=topicDetail(data,t.id);return !!(note?.note||note?.blocker||note?.next_step)});
 const practice=data.workspace.practice.filter(p=>p.subject===selected);
 const activeView=sectionNames.includes(view)?view:'overview';
 const showReward=(id?:string)=>onNavigate({tab:'rewards',subject:selected,...(id?{recordId:id,recordKind:'badge'}:{})});
 return <div className="subject-hub"><div className="page-heading"><div><p className="eyebrow">Everything for your subject</p><h1>Your subjects</h1><p className="muted">Choose a subject to find its learning path, notes, practice, and rewards.</p></div><span className="chip"><BookOpen size={17}/>{subject.name}</span></div>
 <SubjectPicker selected={selected} choose={choose}/>
 <section className="panel subject-hub-header" aria-label={`${subject.name} study summary`}><div><h2><span style={{color:subject.color}}>{subject.glyph}</span> {subject.name}</h2><p className="muted">{formatTime(studied)} studied · Study level {level.level} · {earned.length} rewards earned</p></div><div className="action-row"><button className="primary-button" disabled={!loaded||pending} onClick={()=>onStudy(selected,null,data.settings.focusMinutes)}><Play size={17}/> Start studying</button><button className="secondary-button" disabled={!loaded||pending} onClick={()=>onAssistant(selected)}><Sparkles size={17}/> Generate an AI lesson</button></div><p className="small-note subject-hub-start-hint">Start studying opens your timer setup. You choose when to start. AI lessons use the assistant selected in Settings and require an internet connection.</p></section>
 <Tabs value={activeView} onValueChange={onView}><TabsList className="tabs-list subject-hub-tabs" aria-label={`${subject.name} sections`}><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="learning">Learning path</TabsTrigger><TabsTrigger value="notes">Notes</TabsTrigger><TabsTrigger value="practice">Practice</TabsTrigger><TabsTrigger value="rewards">Rewards</TabsTrigger></TabsList>
 <TabsContent value="overview"><div className="subject-hub-grid"><section className="panel"><p className="eyebrow">Your next step</p><h2>{language?'Build your vocabulary':nextTopic?.title??'Choose your next question'}</h2><p className="muted">{language?`${(data.wordCounts[selected]??0).toLocaleString()} words studied. Add your new words, review earlier words, or try a language practice challenge.`:nextTopic?.criterion??'Add a personal topic about something you want to understand or practice.'}</p><button className="primary-button" disabled={!loaded} onClick={()=>language?onView('learning'):onOpenTopic(nextTopic?.id??'new')}><BookOpen size={16}/>{language?'Open vocabulary & learning path':nextTopic?'Open this topic':'Add a personal topic'}</button>{!language&&<p className="small-note">{learned} / {topics.length} topics self-assessed. Checkmarks record your own assessment.</p>}</section>
 <section className="panel"><p className="eyebrow">A place for your questions</p><h2>Your study notes</h2><p className="muted">Keep what you want to understand, where you get stuck, and your next small step together with each topic.</p>{notes.slice(0,2).map(t=><button key={t.id} className="subject-hub-item" onClick={()=>onOpenTopic(t.id)}><FileText size={16}/><span>{t.title}</span><ArrowRight size={16}/></button>)}<button className="secondary-button" onClick={()=>onView('notes')}>Open notes · {notes.length} saved</button></section>
 <section className="panel"><p className="eyebrow">Use what you learned</p><h2>Practice & evidence</h2><p className="muted">{practice.length} completed practice {practice.length===1?'entry':'entries'}. Record an exercise, drawing, explanation, or project.</p><button className="secondary-button" onClick={()=>onView('practice')}>Record completed practice</button></section>
 <section className="panel"><p className="eyebrow">Your next rewards</p><h2>{earned.length} earned for {subject.name}</h2>{[nextWords,nextTime].filter(a=>!!a).map(a=><div className="subject-hub-reward" key={a!.id}><strong>{a!.name}</strong><p className="muted">{a!.detail}</p><Progress value={a!.progress} aria-label={`${a!.name} progress`}/></div>)}<button className="secondary-button" onClick={()=>onView('rewards')}><Trophy size={16}/> Explore rewards</button></section></div></TabsContent>
 <TabsContent value="learning"><LearningPath embedded {...{data,selected,choose,act,pending,loaded,onOpenTopic}}/></TabsContent>
 <TabsContent value="notes"><div className="section-title"><div><h2>{subject.name} study notes</h2><p className="muted">Open a topic to write your questions or copy a prompt for your AI Assistant.</p></div><button className="secondary-button" disabled={!loaded||pending} onClick={()=>onOpenTopic('new')}><Plus size={16}/> Add personal topic</button></div>{!topics.length?<section className="panel empty-state"><FileText size={28}/><h3>Your first note starts with a question.</h3><p>Add a personal topic to keep your study direction here.</p></section>:<div className="subject-hub-grid">{[...topics].sort((a,b)=>Number(notes.some(t=>t.id===b.id))-Number(notes.some(t=>t.id===a.id))).map(t=>{const detail=topicDetail(data,t.id);return <article className="panel subject-hub-note" key={t.id}><span className="difficulty-label">{topicDifficulty(t.id)??'Personal topic'}</span><h3>{t.title}</h3><p className="muted">{understanding[topicLevel(data,t.id)]}</p><p className="subject-hub-note-preview">{detail?.note||detail?.blocker||detail?.next_step||'No note yet. Write what you want to understand more deeply.'}</p><button className="secondary-button" onClick={()=>onOpenTopic(t.id)}>Open topic & note</button></article>})}</div>}</TabsContent>
 <TabsContent value="practice"><SubjectPractice key={selected} {...props}/></TabsContent>
 <TabsContent value="rewards"><div className="section-title"><div><h2>{subject.name} rewards</h2><p className="muted">Earn rewards for study time, learning, practice, reviews, and completed goals.</p></div><button className="secondary-button" onClick={()=>showReward()}><Trophy size={16}/> See all subject rewards</button></div><div className="subject-hub-grid">{upcoming.slice(0,3).map(a=><article className="panel subject-hub-reward" key={a.id}><p className="eyebrow">Coming up next</p><Trophy size={24}/><h3>{a.name}</h3><p className="muted">{a.detail}</p><Progress value={a.progress} aria-label={`${a.name} progress`}/></article>)}{earned.slice(-3).reverse().map(a=><article className="panel subject-hub-reward" key={a.id}><p className="eyebrow">Earned reward</p><Trophy size={24}/><h3>{a.name}</h3><p className="muted">{a.detail}</p><button className="secondary-button" onClick={()=>showReward(a.id)}>Open reward</button></article>)}</div><p className="small-note">Study levels show time invested. Learning and vocabulary rewards reflect the progress you record.</p></TabsContent>
 </Tabs></div>;
}

type PracticeDraft={topicId:string;title:string;reflection:string};
function SubjectPractice({data,selected,act,pending,loaded,onOpenTopic,onNavigate}:Props){
 const key=`atlas-subject-practice-draft-${selected}`,topics=availableTopics(data).filter(t=>t.subject===selected);
 const [draft,setDraft]=useState<PracticeDraft>(()=>{try{const saved=JSON.parse(localStorage.getItem(key)??'null');return {topicId:typeof saved?.topicId==='string'?saved.topicId:'',title:typeof saved?.title==='string'?saved.title:'',reflection:typeof saved?.reflection==='string'?saved.reflection:''}}catch{return {topicId:'',title:'',reflection:''}}});
 const retry=useRef<{id:string;signature:string}|null>(null);
 const change=(update:Partial<PracticeDraft>)=>setDraft(previous=>{const next={...previous,...update};try{localStorage.setItem(key,JSON.stringify(next))}catch{}return next});
 useEffect(()=>{if(draft.topicId&&!topics.some(t=>t.id===draft.topicId))change({topicId:''})},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();const signature=JSON.stringify(draft);if(retry.current?.signature!==signature)retry.current={id:crypto.randomUUID(),signature};try{await act({action:'practice-add',id:retry.current!.id,subject:selected,topicId:draft.topicId||null,title:draft.title.trim(),reflection:draft.reflection.trim(),link:''});retry.current=null;change({topicId:'',title:'',reflection:''});toast.success('Completed practice saved')}catch{}};
 const entries=data.workspace.practice.filter(p=>p.subject===selected).sort((a,b)=>b.completed_at-a.completed_at);
 return <><div className="section-title"><div><h2>Practice what you learned</h2><p className="muted">Record completed work. Your draft stays on this computer while you move between sections.</p></div><button className="secondary-button" onClick={()=>onNavigate({tab:'today',view:'gallery',subject:selected})}>Open evidence gallery</button></div>{!isLanguage(selected)&&topics.some(t=>practiceBanks[t.id])&&<section className="panel"><h3>Offline exercise banks</h3><p className="muted">Choose a topic for guided tasks, independent practice, hints, worked solutions and fresh review.</p><div className="topic-chips">{topics.filter(t=>practiceBanks[t.id]).map(t=><button key={t.id} onClick={()=>onOpenTopic(t.id)}>{t.title} · {practiceEvidence(t.id,data.workspace.exerciseAttempts??[]).attempted} attempted</button>)}</div></section>}<div className="subject-hub-grid"><section className="panel"><h3>Record completed practice</h3><form onSubmit={save}><label>Topic (optional)<select value={draft.topicId} onChange={e=>change({topicId:e.target.value})}><option value="">General subject practice</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>What I practiced *<input required maxLength={180} value={draft.title} onChange={e=>change({title:e.target.value})} placeholder="Solving three force problems"/></label><label>What I completed or learned *<textarea required rows={5} maxLength={5000} value={draft.reflection} onChange={e=>change({reflection:e.target.value})} placeholder="Describe your work, what helped, and what you want to improve."/></label><button className="primary-button" type="submit" disabled={pending||!loaded||!draft.title.trim()||!draft.reflection.trim()}>Save completed practice</button></form>{draft.topicId&&<button className="text-button" onClick={()=>onOpenTopic(draft.topicId)}>Open this topic’s practice challenge</button>}<p className="small-note">* Required. Attach files and evidence links in the evidence gallery or a topic’s study note.</p></section><section className="panel"><h3>{isLanguage(selected)?'Ideas for language practice':'Your recent practice'}</h3>{isLanguage(selected)&&<ul className="subject-hub-practice-ideas">{(languageChallenges[selected]??[]).map(item=><li key={item.title}><strong>{item.title}</strong><p className="muted">{item.task}</p><button className="text-button" onClick={()=>change({title:item.title})}>Use this title</button></li>)}</ul>}{!entries.length?<p className="muted">Your completed practice will appear here.</p>:entries.slice(0,5).map(entry=><button className="subject-hub-item" key={entry.id} onClick={()=>onNavigate({tab:'today',view:'gallery',subject:selected,recordKind:'practice',recordId:entry.id})}><Clock size={16}/><span><strong>{entry.title}</strong><small>{new Date(entry.completed_at).toLocaleDateString()}</small></span><ArrowRight size={16}/></button>)}</section></div></>;
}
