import {topicDifficulty} from '@/lib/difficulty';
import LessonReader from './lesson-reader';
import {offlineFetch as fetch,evidenceUrl} from '@/lib/offline-api';
"use client";
import {useEffect,useRef,useState} from 'react';
import {Copy,BookOpen,Check,Upload,Play,ArrowUpRight} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {subjects,type Snapshot,type SubjectId} from '@/lib/study';
import {availableTopics,topicDetail,topicLevel,understanding,studyPrompt} from '@/lib/workspace';
import guidance from '@/lib/learning-guidance.json';
type Props={id:string;data:Snapshot;selected:SubjectId;pending:boolean;act:(c:Record<string,unknown>)=>Promise<Snapshot>;onClose:()=>void;onOpen:(id:string)=>void;onCreated:(id:string)=>void;onStudy:(subject:SubjectId,topicId:string,minutes:number)=>void;refresh:()=>Promise<void>};
export default function TopicStudio({id,data,selected,pending,act,onClose,onOpen,onCreated,onStudy,refresh}:Props){
 const topics=availableTopics(data),topic=topics.find(t=>t.id===id),detail=topicDetail(data,id),isNew=id==='new';
 const draftKey=`atlas-topic-draft-${id}`;const recovered=(()=>{try{return JSON.parse(localStorage.getItem(draftKey)??'null')}catch{return null}})();
 const [subject,setSubject]=useState<SubjectId>(topic?.subject??selected),[title,setTitle]=useState(topic?.title??''),[note,setNote]=useState(recovered?.note??detail?.note??''),[blocker,setBlocker]=useState(recovered?.blocker??detail?.blocker??''),[nextStep,setNextStep]=useState(recovered?.nextStep??detail?.next_step??''),[reflection,setReflection]=useState(''),[link,setLink]=useState(''),[savingFile,setSavingFile]=useState(false),[promptOpen,setPromptOpen]=useState(false);
 const practiceRetry=useRef<string|null>(null),customId=useRef(crypto.randomUUID()),upload=useRef<HTMLInputElement>(null);
 const level=topic?topicLevel(data,id):0,guide=(guidance.topics as Record<string,{practice_challenge:string;explain_it_prompt:string;prerequisites:string[]}>)[id],preparation=guide?.prerequisites.map(id=>topics.find(t=>t.id===id)).filter(t=>!!t)??[];
 const prompt=studyPrompt(subject,title,note,blocker,level,nextStep),unsaved=note!==(detail?.note??'')||blocker!==(detail?.blocker??'')||nextStep!==(detail?.next_step??'');
 useEffect(()=>{if(isNew||!unsaved)return;try{localStorage.setItem(draftKey,JSON.stringify({note,blocker,nextStep}))}catch{}if(pending)return;const timeout=setTimeout(()=>{void fetch('/api/study',{method:'POST',body:JSON.stringify({action:'topic-note',topicId:id,note,blocker,nextStep})}).then(async res=>{if(res.ok){try{if(localStorage.getItem(draftKey)===JSON.stringify({note,blocker,nextStep}))localStorage.removeItem(draftKey)}catch{}await refresh()}else toast.error('Study note could not autosave. Your draft is kept for retry.')})},650);return()=>clearTimeout(timeout)},[note,blocker,nextStep,pending,unsaved,isNew,id]);
 const keepDraft=(value:{note:string;blocker:string;nextStep:string})=>{try{localStorage.setItem(draftKey,JSON.stringify(value))}catch{}};
 const save=async()=>{try{if(isNew){const newId=customId.current;await act({action:'topic-create',id:newId,subject,title,note});onCreated(newId)}else await act({action:'topic-note',topicId:id,note,blocker,nextStep});try{if(localStorage.getItem(draftKey)===JSON.stringify({note,blocker,nextStep}))localStorage.removeItem(draftKey)}catch{}toast.success('Study note saved');return true}catch{return false}};
 const copy=async()=>{try{await navigator.clipboard.writeText(prompt);toast.success('AI Assistant study prompt copied',{description:'Paste it into your AI Assistant conversation.'})}catch{setPromptOpen(true);toast('Select and copy the prompt below.')}if(!isNew&&unsaved)await save()};
 const recordPractice=async(e:React.FormEvent)=>{e.preventDefault();if(link){try{const url=new URL(link);if(url.protocol!=='https:'||url.username||url.password)throw Error()}catch{toast.error('Use an HTTPS evidence link without a username or password, or leave it blank.');return}}practiceRetry.current??=crypto.randomUUID();try{await act({action:'practice-add',id:practiceRetry.current,subject,topicId:id,title:`${title} practice`.slice(0,180),reflection,link});practiceRetry.current=null;setReflection('');setLink('');toast.success('Completed practice saved')}catch{}};
 const addFile=async(file:File)=>{setSavingFile(true);try{const form=new FormData();form.set('file',file);form.set('subject',subject);form.set('topicId',id);const res=await fetch('/api/evidence',{method:'POST',body:form}),body=await res.json() as {error?:string};if(!res.ok)throw Error(body.error);await refresh();toast.success('File saved to your local gallery')}catch(e){toast.error(e instanceof Error?e.message:'File could not save.')}finally{setSavingFile(false);if(upload.current)upload.current.value=''}};
 return <Dialog open onOpenChange={open=>{if(!open){if(unsaved&&!isNew)void save().then(ok=>{if(ok)onClose()});else onClose()}}}><DialogContent className="form-dialog topic-studio"><DialogTitle>{isNew?'Add a personal topic':title}</DialogTitle><DialogDescription>{isNew?'Choose something you want to explore. Your note can become a focused AI Assistant study prompt.':`${subjects.find(s=>s.id===subject)?.name} · ${topicDifficulty(id)??'Personal topic'} · Your notes, understanding, and practice`}</DialogDescription>
 {isNew?<form onSubmit={e=>{e.preventDefault();void save()}}><label>Subject<Select value={subject} onValueChange={v=>setSubject(v as SubjectId)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{subjects.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select></label><label>Topic title<input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Understanding why German word order changes"/></label><label>What I want to understand<textarea maxLength={5000} rows={5} value={note} onChange={e=>{keepDraft({note:e.target.value,blocker,nextStep});setNote(e.target.value)}} placeholder="Describe the questions, examples, or approach that would help you."/></label><button className="primary-button" type="submit" disabled={pending||!title.trim()}>Save personal topic</button></form>:<>
 <div className="studio-toolbar"><label>My understanding<Select value={String(level)} onValueChange={v=>void act({action:'topic-level',topicId:id,level:Number(v)}).catch(()=>{})} disabled={pending}><SelectTrigger aria-label="My understanding"><SelectValue/></SelectTrigger><SelectContent>{understanding.map((label,i)=><SelectItem value={String(i)} key={i}>{label}</SelectItem>)}</SelectContent></Select></label><button className="secondary-button" disabled={pending} onClick={()=>{const start=()=>{onStudy(subject,id,data.settings.focusMinutes);onClose()};if(unsaved)void save().then(ok=>{if(ok)start()});else start()}}><Play size={16}/> Study this topic</button></div>
 <p className="small-note">Choose a level after checking what you can do. These are your own assessments; practice and recall can be checked again.</p>
 {!!preparation.length&&<div className="preparation"><p className="eyebrow">Suggested preparation</p>{preparation.map(t=><button key={t!.id} className="topic-preparation" onClick={()=>{if(unsaved)void save().then(ok=>{if(ok)onOpen(t!.id)});else onOpen(t!.id)}}>{topicLevel(data,t!.id)>=2?<Check size={14}/>:<BookOpen size={14}/>} {t!.title} <ArrowUpRight size={14}/></button>)}<p className="muted">Open a preparation topic to review it or mark the understanding you already have.</p></div>}
 <LessonReader id={id} data={data} pending={pending} act={act}/>
 <section className="studio-section"><div className="section-title compact"><h2>My study direction</h2><span className="muted" aria-live="polite">{unsaved?'Unsaved changes':'Saved note'}</span></div><label>What I want to understand more deeply<textarea aria-label="What I want to understand more deeply" value={note} maxLength={5000} rows={5} onChange={e=>{keepDraft({note:e.target.value,blocker,nextStep});setNote(e.target.value)}} placeholder="I want an intuitive explanation, with visual examples. I get confused when…"/></label><label>Where I get stuck<textarea value={blocker} maxLength={2000} rows={2} onChange={e=>{keepDraft({note,blocker:e.target.value,nextStep});setBlocker(e.target.value)}} placeholder="A question, recurring mistake, or missing piece."/></label><label>My next small step<input value={nextStep} maxLength={1000} onChange={e=>{keepDraft({note,blocker,nextStep:e.target.value});setNextStep(e.target.value)}} placeholder="Work through one example and explain each step."/></label><div className="action-row"><button className="primary-button" disabled={pending} onClick={()=>void save()}>Save note</button><button className="secondary-button" disabled={pending} onClick={()=>void copy()}><Copy size={16}/> Copy AI Assistant study prompt</button></div><details open={promptOpen} onToggle={e=>setPromptOpen(e.currentTarget.open)}><summary>Preview the prompt</summary><textarea aria-label="AI Assistant study prompt" readOnly value={prompt} rows={8} className="prompt-preview"/></details></section>
 <section className="studio-section"><p className="eyebrow">Explain & apply</p><h2>Try it in practice</h2><p className="practice-task">{guide?.practice_challenge??`Create a small example or project that uses ${title}. Explain the choices you made.`}</p><p className="muted">Explain it: {guide?.explain_it_prompt??`How would you explain ${title} to someone new to it?`}</p><form onSubmit={recordPractice}><label>What I completed or learned<textarea required value={reflection} maxLength={5000} rows={3} onChange={e=>setReflection(e.target.value)} placeholder="Describe what you did, what worked, and what you want to improve."/></label><label>HTTPS evidence link (optional)<input type="url" pattern="[Hh][Tt][Tt][Pp][Ss]://.*" title="Use a link starting with https://, or leave it blank." maxLength={2000} value={link} onChange={e=>setLink(e.target.value)} placeholder="https://…"/></label><button type="submit" className="primary-button" disabled={pending||!reflection.trim()}>Save completed practice</button></form><p className="small-note">Record completed work here. Your first practice and later milestones unlock collection rewards automatically.</p></section>
 {level>0&&<section className="studio-section"><h2>Check your recall</h2><p className="muted">Try explaining the topic without your notes, then choose how it went. Atlas will schedule the next review.</p><div className="action-row review-actions">{[['easy','Easy to recall'],['uncertain','Some uncertainty'],['practice','Needs practice']].map(([confidence,label])=><button key={confidence} className="secondary-button" disabled={pending} onClick={()=>void act({action:'topic-review',topicId:id,confidence}).then(()=>toast.success('Review saved')).catch(()=>{})}>{label}</button>)}</div>{detail?.review_at&&<p className="small-note">Next review: {new Date(detail.review_at).toLocaleString()} · {detail.review_count} reviews recorded</p>}</section>}
 <section className="studio-section"><div className="section-title compact"><h2>Private evidence</h2><button className="secondary-button" disabled={savingFile||pending} onClick={()=>upload.current?.click()}><Upload size={16}/>{savingFile?'Saving…':'Attach a file'}</button></div><input ref={upload} type="file" className="hidden-file" accept="image/png,image/jpeg,image/webp,image/gif,application/pdf,.txt,.md,.csv,.json" aria-label="Attach topic evidence" onChange={e=>{if(e.target.files?.[0])void addFile(e.target.files[0])}}/><p className="muted">Drawings, exercises, PDFs, or text. Up to 5 MB each; 20 MB of files in your private gallery.</p><div className="topic-file-list">{data.workspace.files.filter(f=>f.topic_id===id).map(f=><a key={f.id} href={evidenceUrl(f.id)} target="_blank" rel="noopener noreferrer">{f.filename} <ArrowUpRight size={14}/></a>)}</div>{data.workspace.practice.filter(p=>p.topic_id===id).slice(0,3).map(p=><article key={p.id} className="practice-saved"><p className="eyebrow">Completed {new Date(p.completed_at).toLocaleDateString()}</p><p>{p.reflection}</p>{p.link&&<a href={p.link} target="_blank" rel="noopener noreferrer">Open evidence link ↗</a>}</article>)}</section>
 </>}
 </DialogContent></Dialog>
}
